// DO NOT EDIT — generated by packages/design-engine/scripts/semantic-tokens-gen.ts
// (`bun run tokens:reference`; `bun run tokens:reference:check` fails when this is stale).
// Source: packages/blocks/src/lib/style/semantic.css, plus foundation.css for the
// OKLCH lightness of each stop in the default chassis.
//
// The surface / text / border tables and the intent roles of the CSS token
// reference (`urbicon css-reference`, `get_css_reference`) render from this, so
// the reference cannot state a stop the CSS does not have. Role sentences are the
// `@role` / `@absent` markers in semantic.css — edit them there.

import type { SemanticTokens } from './semantic-tokens.js';

export const SEMANTIC_TOKENS: SemanticTokens = {
  families: {
    surface: [
      {
        name: 'surface-base',
        role: 'L·1 — the page itself: content, cards and reading surfaces sit at this level',
        light: { ref: 'neutral-0', l: 1 },
        dark: { ref: 'neutral-900', l: 0.15 }
      },
      {
        name: 'surface-quiet',
        role: 'L·0 — the ground beneath the page; the softest in-page tint, which alone signals "own zone" without border or shadow',
        light: { ref: 'neutral-25', l: 0.985 },
        dark: { ref: 'neutral-850', l: 0.18 }
      },
      {
        name: 'surface-elevated',
        role: 'L·2 — lifted surfaces (Popover, Menu, Select dropdown), above the page with shadow and a z-index of their own',
        light: { ref: 'neutral-50', l: 0.965 },
        dark: { ref: 'neutral-800', l: 0.23 }
      },
      {
        name: 'surface-overlay',
        role: 'L·3 — the highest surfaces (Dialog, Drawer, Sheet, Toast), full shadow plus backdrop dimming',
        light: { ref: 'neutral-0', l: 1 },
        dark: { ref: 'neutral-850', l: 0.18 }
      },
      {
        name: 'surface-interactive',
        role: 'a resting FILL one step in from the page — a filled Input, a Slider track, the Tab list; its hover step is surface-interactive-hover',
        light: { ref: 'neutral-100', l: 0.95 },
        dark: { ref: 'neutral-700', l: 0.32 }
      },
      {
        name: 'surface-interactive-hover',
        role: 'the hover step for an element resting on surface-interactive — it continues the fill\'s own ladder, where surface-hover would be a no-op',
        light: { ref: 'neutral-200', l: 0.89 },
        dark: { ref: 'neutral-650', l: 0.38 }
      },
      {
        name: 'surface-hover',
        role: 'the hover step for an element resting on a READING surface (base / quiet / elevated) — a menu item, a table row',
        light: { ref: 'neutral-100', l: 0.95 },
        dark: { ref: 'neutral-750', l: 0.28 }
      },
      {
        name: 'surface-active',
        role: 'the pressed step for an element resting on a reading surface; the pair of surface-hover',
        light: { ref: 'neutral-200', l: 0.89 },
        dark: { ref: 'neutral-700', l: 0.32 }
      },
      {
        name: 'surface-disabled',
        role: 'the fill of a disabled control',
        light: { ref: 'neutral-100', l: 0.95 },
        dark: { ref: 'neutral-800', l: 0.23 }
      },
      {
        name: 'surface-selected',
        role: 'the ground of a selected item — the primary intent\'s tint, not a neutral step',
        light: { ref: 'primary-50', l: 0.95 },
        dark: { ref: 'primary-900', l: 0.28 }
      },
      {
        name: 'surface-subtle',
        role: 'a RESTING tint only, never a hover step — it equals surface-elevated; prefer surface-quiet for a zone, surface-elevated for a lift',
        light: { ref: 'neutral-50', l: 0.965 },
        dark: { ref: 'neutral-800', l: 0.23 }
      },
      {
        name: 'surface-inverted',
        role: 'the inverted ground (Tooltip) — near-black in light mode, near-white in dark; pairs with text-inverted',
        light: { ref: 'neutral-900', l: 0.15 },
        dark: { ref: 'neutral-100', l: 0.95 }
      }
    ],
    text: [
      {
        name: 'text-primary',
        role: 'body copy — the top of the informative ramp (primary → secondary → tertiary); each rung clears AA 4.5:1 on every reading surface',
        light: { ref: 'neutral-900', l: 0.15 },
        dark: { ref: 'neutral-100', l: 0.95 }
      },
      {
        name: 'text-inverted',
        role: 'text on surface-inverted',
        light: { ref: 'neutral-0', l: 1 },
        dark: { ref: 'neutral-900', l: 0.15 }
      },
      {
        name: 'text-secondary',
        role: 'supporting text — the second rung of the informative ramp',
        light: { ref: 'neutral-700', l: 0.32 },
        dark: { ref: 'neutral-300', l: 0.83 }
      },
      {
        name: 'text-tertiary',
        role: 'muted text and metadata — the last rung that is still body-safe (AA on every reading surface); reach for it wherever quaternary tempts',
        light: { ref: 'neutral-600', l: 0.42 },
        dark: { ref: 'neutral-300', l: 0.83 }
      },
      {
        name: 'text-quaternary',
        role: 'MARK-ONLY — placeholders, dense-grid marks, disabled glyphs, decoration; never use it for body text (held only to the 3:1 UI floor)',
        light: { ref: 'neutral-500', l: 0.55 },
        dark: { ref: 'neutral-400', l: 0.7 }
      },
      {
        name: 'text-disabled',
        role: 'disabled text — the weakest rung, held to the 3:1 UI floor so a disabled field\'s label still says what the field is',
        light: { ref: 'neutral-500', l: 0.55 },
        dark: { ref: 'neutral-500', l: 0.55 }
      },
      {
        name: 'text-link',
        role: 'link ink on a reading surface — aliases the primary intent\'s -text role (its AA text step), never the base fill',
        alias: 'primary-text',
        light: { ref: 'primary-700', l: 0.44 },
        dark: { ref: 'primary-400', l: 0.66 }
      },
      {
        name: 'text-on-dark',
        role: 'the label on the avatar identity palette (one lightness per mode by construction); deliberately not aliased to text-on-fill',
        light: { ref: 'neutral-0', l: 1 },
        dark: { ref: 'neutral-900', l: 0.15 }
      },
      {
        name: 'text-on-fill',
        role: 'the label on ANY solid intent fill — white in light mode, near-black in dark mode; warning is the exception (text-on-warning)',
        light: { ref: 'neutral-0', l: 1 },
        dark: { ref: 'neutral-900', l: 0.15 }
      },
      {
        name: 'text-on-primary',
        role: 'the label on the primary fill specifically — defaults to text-on-fill; override it to repaint the primary fills alone',
        alias: 'text-on-fill',
        light: { ref: 'neutral-0', l: 1 },
        dark: { ref: 'neutral-900', l: 0.15 }
      },
      {
        name: 'text-on-warning',
        role: 'the label on the warning fill — a warm dark from the ramp\'s own 950 stop in BOTH modes, because the fill stays light amber in both',
        light: { ref: 'warning-950', l: 0.15 },
        dark: { ref: 'warning-950', l: 0.15 }
      },
      {
        name: 'text-on-surface',
        role: 'text on any surface — it tracks the page background, so never on an intent fill',
        light: { ref: 'neutral-900', l: 0.15 },
        dark: { ref: 'neutral-100', l: 0.95 }
      }
    ],
    border: [
      {
        name: 'border-hairline',
        role: 'the quietest tier — structural dividers (row dividers, Card separators); translucent, so it blends onto any surface',
        light: { raw: 'rgb(0 0 0 / 0.08)' },
        dark: { raw: 'rgb(255 255 255 / 0.06)' }
      },
      {
        name: 'border-subtle',
        role: 'quiet container outlines (Popover) — one tier above hairline',
        light: { ref: 'neutral-200', l: 0.89 },
        dark: { ref: 'neutral-700', l: 0.32 }
      },
      {
        name: 'border-default',
        role: 'the standard border of controls and containers',
        light: { ref: 'neutral-300', l: 0.83 },
        dark: { ref: 'neutral-600', l: 0.42 }
      },
      {
        name: 'border-emphasis',
        role: 'an emphasised outline, one step stronger than default',
        light: { ref: 'neutral-400', l: 0.7 },
        dark: { ref: 'neutral-500', l: 0.55 }
      },
      {
        name: 'border-strong',
        role: 'the strongest outline the chassis offers',
        light: { ref: 'neutral-500', l: 0.55 },
        dark: { ref: 'neutral-400', l: 0.7 }
      }
    ]
  },
  intents: {
    exemplar: 'primary',
    roles: [
      { suffix: 'base', role: 'the FILL — a surface with text-on-fill sitting on it; never a text colour (variants-lint errors on a text-<intent> class)' },
      { suffix: 'hover', role: 'the hover step of the fill' },
      { suffix: 'active', role: 'the pressed step of the fill' },
      { suffix: 'subtle', role: 'a soft tinted ground in the intent\'s hue — an Alert\'s background, a selected row' },
      { suffix: 'text', role: 'the intent as TEXT on a reading surface — the nearest stop that clears AA 4.5:1 on every reading surface and the intent\'s own -subtle' },
      { suffix: 'emphasis', role: 'the near-ink tier — strong statements as text, and doubles as a fill; the Radix steps 11/12 split with -text' }
    ],
    entries: [
      {
        name: 'primary',
        stops: {
          base: {
            light: { ref: 'primary-600', l: 0.52 },
            dark: { ref: 'primary-500', l: 0.58 }
          },
          hover: {
            light: { ref: 'primary-700', l: 0.44 },
            dark: { ref: 'primary-400', l: 0.66 }
          },
          active: {
            light: { ref: 'primary-800', l: 0.36 },
            dark: { ref: 'primary-300', l: 0.74 }
          },
          subtle: {
            light: { ref: 'primary-50', l: 0.95 },
            dark: { ref: 'primary-900', l: 0.28 }
          },
          text: {
            light: { ref: 'primary-700', l: 0.44 },
            dark: { ref: 'primary-400', l: 0.66 }
          },
          emphasis: {
            light: { ref: 'primary-900', l: 0.28 },
            dark: { ref: 'primary-200', l: 0.82 }
          }
        }
      },
      {
        name: 'secondary',
        stops: {
          base: {
            light: { ref: 'secondary-500', l: 0.55 },
            dark: { ref: 'secondary-400', l: 0.66 }
          },
          hover: {
            light: { ref: 'secondary-600', l: 0.48 },
            dark: { ref: 'secondary-300', l: 0.74 }
          },
          active: {
            light: { ref: 'secondary-700', l: 0.4 },
            dark: { ref: 'secondary-200', l: 0.82 }
          },
          subtle: {
            light: { ref: 'secondary-50', l: 0.95 },
            dark: { ref: 'secondary-900', l: 0.25 }
          },
          text: {
            light: { ref: 'secondary-600', l: 0.48 },
            dark: { ref: 'secondary-400', l: 0.66 }
          },
          emphasis: {
            light: { ref: 'secondary-800', l: 0.32 },
            dark: { ref: 'secondary-200', l: 0.82 }
          }
        }
      },
      {
        name: 'neutral',
        stops: {
          base: {
            light: { ref: 'warm-neutral-500', l: 0.5, derived: true },
            dark: { ref: 'warm-neutral-400', l: 0.65, derived: true }
          },
          hover: {
            light: { ref: 'warm-neutral-600', l: 0.42, derived: true },
            dark: { ref: 'warm-neutral-300', l: 0.78, derived: true }
          },
          active: {
            light: { ref: 'warm-neutral-700', l: 0.35, derived: true },
            dark: { ref: 'warm-neutral-200', l: 0.86, derived: true }
          },
          subtle: {
            light: { ref: 'warm-neutral-50', l: 0.96, derived: true },
            dark: { ref: 'warm-neutral-900', l: 0.2, derived: true }
          },
          emphasis: {
            light: { ref: 'warm-neutral-800', l: 0.28, derived: true },
            dark: { ref: 'warm-neutral-200', l: 0.86, derived: true }
          }
        }
      },
      {
        name: 'success',
        stops: {
          base: {
            light: { ref: 'success-500', l: 0.5 },
            dark: { ref: 'success-400', l: 0.62 }
          },
          hover: {
            light: { ref: 'success-600', l: 0.44 },
            dark: { ref: 'success-300', l: 0.74 }
          },
          active: {
            light: { ref: 'success-700', l: 0.38 },
            dark: { ref: 'success-200', l: 0.82 }
          },
          subtle: {
            light: { ref: 'success-50', l: 0.95 },
            dark: { ref: 'success-900', l: 0.22 }
          },
          text: {
            light: { ref: 'success-600', l: 0.44 },
            dark: { ref: 'success-400', l: 0.62 }
          },
          emphasis: {
            light: { ref: 'success-800', l: 0.3 },
            dark: { ref: 'success-200', l: 0.82 }
          }
        }
      },
      {
        name: 'warning',
        stops: {
          base: {
            light: { ref: 'warning-500', l: 0.75 },
            dark: { ref: 'warning-400', l: 0.66 }
          },
          hover: {
            light: { ref: 'warning-600', l: 0.65 },
            dark: { ref: 'warning-300', l: 0.74 }
          },
          active: {
            light: { ref: 'warning-700', l: 0.59 },
            dark: { ref: 'warning-200', l: 0.82 }
          },
          subtle: {
            light: { ref: 'warning-50', l: 0.95 },
            dark: { ref: 'warning-900', l: 0.25 }
          },
          text: {
            light: { ref: 'warning-800', l: 0.45 },
            dark: { ref: 'warning-400', l: 0.66 }
          },
          emphasis: {
            light: { ref: 'warning-800', l: 0.45 },
            dark: { ref: 'warning-200', l: 0.82 }
          }
        }
      },
      {
        name: 'danger',
        stops: {
          base: {
            light: { ref: 'danger-500', l: 0.5 },
            dark: { ref: 'danger-400', l: 0.62 }
          },
          hover: {
            light: { ref: 'danger-600', l: 0.44 },
            dark: { ref: 'danger-300', l: 0.74 }
          },
          active: {
            light: { ref: 'danger-700', l: 0.38 },
            dark: { ref: 'danger-200', l: 0.82 }
          },
          subtle: {
            light: { ref: 'danger-50', l: 0.95 },
            dark: { ref: 'danger-900', l: 0.22 }
          },
          text: {
            light: { ref: 'danger-500', l: 0.5 },
            dark: { ref: 'danger-300', l: 0.74 }
          },
          emphasis: {
            light: { ref: 'danger-800', l: 0.3 },
            dark: { ref: 'danger-200', l: 0.82 }
          }
        }
      },
      {
        name: 'info',
        stops: {
          base: {
            light: { ref: 'info-500', l: 0.54 },
            dark: { ref: 'info-400', l: 0.66 }
          },
          hover: {
            light: { ref: 'info-600', l: 0.48 },
            dark: { ref: 'info-300', l: 0.76 }
          },
          active: {
            light: { ref: 'info-700', l: 0.4 },
            dark: { ref: 'info-200', l: 0.84 }
          },
          subtle: {
            light: { ref: 'info-50', l: 0.96 },
            dark: { ref: 'info-900', l: 0.24 }
          },
          text: {
            light: { ref: 'info-600', l: 0.48 },
            dark: { ref: 'info-400', l: 0.66 }
          },
          emphasis: {
            light: { ref: 'info-800', l: 0.32 },
            dark: { ref: 'info-200', l: 0.84 }
          }
        }
      }
    ],
    notes: [
      { intent: 'warning', suffix: 'text', note: 'the light stop is -800, the only rung of a yellow ramp that reads on white — it lands amber-brown while the fill stays yellow' },
      { intent: 'danger', suffix: 'text', note: 'the light stop is the base stop, red already reads on paper; dark needs -300 because sRGB red is too dim on the lightened panels at -400' }
    ],
    absent: [
      { intent: 'neutral', suffix: 'text', reason: 'its base already clears AA as text on every ground in every theme, so a -text role would only alias the base' }
    ]
  },
  notTabled: [
    '--color-skeleton-shimmer',
    '--color-chart-1',
    '--color-chart-2',
    '--color-chart-3',
    '--color-chart-4',
    '--color-chart-5',
    '--color-chart-6',
    '--color-avatar-1',
    '--color-avatar-2',
    '--color-avatar-3',
    '--color-avatar-4',
    '--color-avatar-5',
    '--color-avatar-6',
    '--color-avatar-7',
    '--color-avatar-8',
    '--color-avatar-9',
    '--color-avatar-10',
    '--color-avatar-11',
    '--color-avatar-12',
    '--color-live',
    '--color-interactive-hover',
    '--color-interactive-active',
    '--color-interactive-focus',
    '--color-interactive-disabled',
    '--color-feedback-info',
    '--color-feedback-info-subtle',
    '--color-feedback-success',
    '--color-feedback-success-subtle',
    '--color-feedback-warning',
    '--color-feedback-warning-subtle',
    '--color-feedback-error',
    '--color-feedback-error-subtle',
    '--blocks-shadow-scale-xs',
    '--blocks-shadow-scale-sm',
    '--blocks-shadow-scale-base',
    '--blocks-shadow-scale-md',
    '--blocks-shadow-scale-lg'
  ]
};
