<script lang="ts">
  import SeoMeta from '$lib/SeoMeta.svelte';
  import { resolve } from '$app/paths';
  import {
    Alert,
    Avatar,
    Badge,
    Button,
    Card,
    Checkbox,
    Separator,
    Toggle
  } from '@urbicon-ui/blocks';
  import { DocsLayout as DocsPageLayout } from '@urbicon-ui/docs';
  import { generateChassis, generatePalette, previewVars } from '$lib/theme-preview';

  let brandHue = $state(240);
  let brandChroma = $state(0.15);
  let brandLightness = $state(0.58);
  let secondaryHue = $state(280);
  let secondaryChroma = $state(0.12);
  let secondaryAuto = $state(true);
  // Chassis = the neutral ramp that surfaces/text/borders derive from. Auto
  // follows the brand hue so the whole UI shares the accent's temperature;
  // chassisTint scales the (already tiny) per-stop chroma — 0 = pure grayscale.
  let chassisHue = $state(240);
  let chassisAuto = $state(true);
  let chassisTint = $state(1);
  let radius = $state('md');
  let copied = $state(false);

  function computeAutoSecondaryHue(h: number): number {
    return (h + 40) % 360;
  }

  $effect(() => {
    if (secondaryAuto) {
      secondaryHue = computeAutoSecondaryHue(brandHue);
    }
  });

  $effect(() => {
    if (chassisAuto) {
      chassisHue = brandHue;
    }
  });

  // Chassis stops from the shared palette model ($lib/theme-preview.ts) —
  // the ramp profile mirrors foundation.css and is guarded by its test.
  const chassisPalette = $derived(generateChassis(chassisHue, chassisTint));

  // The chassis equals the library default when hue is 240 at full tint —
  // no point emitting a no-op override in that case.
  const chassisIsDefault = $derived(chassisHue === 240 && chassisTint === 1);

  // Shadow tint + neutral chrome follow the chassis, mirroring the shipped
  // colored themes (forest.css:101,104). A grayscale or default chassis has no
  // temperature to match, so it keeps the library defaults — which is exactly
  // what neutral.css does (it ships no :root block at all).
  const emitChromaKnobs = $derived(!chassisIsDefault && chassisTint > 0);

  // Written once, used twice: the CSS output below and the live preview beside
  // it. Two copies of these strings is how a builder ends up previewing warm
  // shadows the file it hands you does not produce.
  const chromaKnobs = $derived({
    shadowTint: `0.2 0.025 ${chassisHue}`,
    neutralChromeHue: String(chassisHue)
  });

  // Library intent hues (foundation.css). An accent landing on one of these is
  // indistinguishable from a status color, so we flag it — and deliberately do
  // NOT auto-retune: which side moves is a design call the author has to make.
  const INTENT_HUES = [
    { name: 'success', hue: 140 },
    { name: 'warning', hue: 80 },
    { name: 'danger', hue: 25 },
    { name: 'info', hue: 220 }
  ] as const;

  // Exclusive: the library's own default primary (240) sits exactly 20° from info
  // (220) and ships without re-tuning it, so 20° is demonstrably fine. An
  // inclusive bound would flag the default palette the moment the page loads.
  const COLLISION_THRESHOLD = 20;

  /** Shortest angular distance between two hues on the 0–360 wheel. */
  function hueDistance(a: number, b: number): number {
    const d = Math.abs(a - b) % 360;
    return d > 180 ? 360 - d : d;
  }

  function collisionsFor(hue: number, role: string) {
    return INTENT_HUES.filter((i) => hueDistance(hue, i.hue) < COLLISION_THRESHOLD).map((i) => ({
      role,
      intent: i.name,
      intentHue: i.hue,
      distance: Math.round(hueDistance(hue, i.hue))
    }));
  }

  const collisions = $derived([
    ...collisionsFor(brandHue, 'Brand'),
    ...collisionsFor(secondaryHue, 'Secondary')
  ]);

  const radiusOptions = [
    { value: 'none', label: 'None', scale: 0 },
    { value: 'sm', label: 'Tight', scale: 0.5 },
    { value: 'md', label: 'Default', scale: 1 },
    { value: 'lg', label: 'Rounded', scale: 2 },
    { value: 'xl', label: 'Extra', scale: 3 },
    { value: 'full', label: 'Pill', scale: -1 }
  ];

  const baseRadii: Record<string, number> = {
    xs: 0.125,
    sm: 0.25,
    md: 0.375,
    lg: 0.5,
    xl: 0.75,
    '2xl': 1,
    '3xl': 1.5,
    '4xl': 2
  };

  const activeRadiusOption = $derived(radiusOptions.find((o) => o.value === radius)!);

  const radiusVars = $derived.by(() => {
    const opt = activeRadiusOption;
    if (opt.scale === 1) return {};
    const vars: Record<string, string> = {};
    for (const [name, base] of Object.entries(baseRadii)) {
      vars[`--radius-${name}`] =
        opt.scale === -1 ? '9999px' : `${(base * opt.scale).toFixed(3)}rem`;
    }
    return vars;
  });

  let palette = $derived(generatePalette(brandHue, brandChroma, brandLightness));
  let secondaryPalette = $derived(generatePalette(secondaryHue, secondaryChroma, 0.55));

  let cssOutput = $derived.by(() => {
    const chassisLabel = chassisTint === 0 ? 'grayscale' : `hue ${chassisHue}`;
    const lines = [
      `@theme {`,
      `  /* Generated by Urbicon UI Theme Builder */`,
      `  /* Primary Hue: ${brandHue} | Secondary Hue: ${secondaryHue} | Chassis: ${chassisLabel} */`,
      ``
    ];
    for (const [shade, value] of Object.entries(palette)) {
      lines.push(`  --color-primary-${shade}: ${value};`);
    }
    lines.push(``);
    for (const [shade, value] of Object.entries(secondaryPalette)) {
      lines.push(`  --color-secondary-${shade}: ${value};`);
    }
    if (!chassisIsDefault) {
      lines.push(``);
      lines.push(`  /* Chassis — neutral ramp re-tinted (${chassisLabel}) so surfaces, text`);
      lines.push(`     and borders share the accent's temperature. Only the hue/chroma`);
      lines.push(`     shift; lightness matches the foundation ramp (WCAG-safe). */`);
      for (const { shade, value } of chassisPalette) {
        lines.push(`  --color-neutral-${shade}: ${value};`);
      }
    }
    const rv = Object.entries(radiusVars);
    if (rv.length > 0) {
      lines.push(``);
      lines.push(`  /* Border Radius – ${activeRadiusOption.label}. The modify,`);
      lines.push(`     contain and bridge tiers read this scale, so they follow it. */`);
      for (const [name, value] of rv) {
        lines.push(`  ${name}: ${value};`);
      }
      lines.push(``);
      lines.push(`  /* --radius-commit is a literal pill and does NOT follow the`);
      lines.push(`     scale. Uncomment it with a literal of your own to square the`);
      lines.push(`     commit tier (Button, Badge, Checkbox); 0 squares it fully. */`);
      lines.push(`  /* --radius-commit: 0.5rem; */`);
      lines.push(`  /* --radius-control (the radio dot) is deliberately not offered`);
      lines.push(`     here: it was split off the pill so squaring your buttons keeps`);
      lines.push(`     the radio a circle, which is the only thing telling it from a`);
      lines.push(`     checkbox. Override it on purpose or not at all. */`);
    }
    lines.push(`}`);
    if (emitChromaKnobs) {
      lines.push(``);
      lines.push(`/* :root, NOT @theme — both are raw partial values spliced into a`);
      lines.push(`   color function, so @theme would drop them on the floor. */`);
      lines.push(`:root {`);
      lines.push(`  /* oklch L C H, no alpha — shadows pick up the chassis temperature`);
      lines.push(`     instead of reading as cool smudges on tinted surfaces. */`);
      lines.push(`  --blocks-shadow-tint: ${chromaKnobs.shadowTint};`);
      lines.push(`  /* Neutral intent chrome (bg-neutral / text-neutral / borders). */`);
      lines.push(`  --neutral-chrome-hue: ${chromaKnobs.neutralChromeHue};`);
      lines.push(`}`);
    }
    if (collisions.length > 0) {
      lines.push(``);
      lines.push(`/* Intent collision — this theme is not finished yet.`);
      for (const c of collisions) {
        lines.push(
          `   ${c.role} hue is only ${c.distance}deg from ${c.intent} (hue ${c.intentHue}) — re-tune`
        );
        lines.push(
          `   the --color-${c.intent}-* ramp 15-25deg away, so a status color still reads`
        );
        lines.push(`   as status rather than as your brand.`);
      }
      lines.push(`   forest.css ships a worked example of exactly this fix. */`);
    }
    return lines.join('\n');
  });

  // Ramps + every role that reads them, re-declared for the preview scope in
  // both modes via light-dark() — shared with /customization/themes
  // ($lib/theme-preview.ts). Passing `radii` pulls the derived tier tokens in
  // too, without which the picker moved nothing in the preview:
  // `--radius-modify: var(--radius-sm)` substitutes at :root, so overriding the
  // base scale in this inline scope left every component on its original
  // corner. The chroma knobs travel the same way — they are what carries the
  // chassis temperature into shadows and neutral chrome — and only when the
  // output file sets them, so the preview shows what the file produces.
  let previewStyle = $derived(
    previewVars({
      palette,
      secondaryPalette,
      chassis: chassisPalette,
      radii: radiusVars,
      shadowTint: emitChromaKnobs ? chromaKnobs.shadowTint : undefined,
      neutralChromeHue: emitChromaKnobs ? chromaKnobs.neutralChromeHue : undefined
    })
  );

  async function copyCSS() {
    await navigator.clipboard.writeText(cssOutput);
    copied = true;
    setTimeout(() => (copied = false), 2000);
  }
</script>

<!-- urbicon-ignore inline-style card-monotony — this page generates OKLCH
     values and has to apply them, which is the whole point of a theme builder;
     a token would show the current theme, not the one being built. The five
     cards are tool panels of equal standing. -->

<!--
  No `<Section>` on this page, deliberately. Its headings label the panels of a
  tool — colour pickers, a live preview, a CSS output panel — laid out in a grid beside their own
  controls, not the parts of a document read top to bottom. `Section` brings a
  header block and document spacing that would fight that layout, and a table of
  contents linking into grid columns helps nobody. The five prose pages under
  /customization use `Section`; these two are the exception, with a reason.
-->

<SeoMeta
  title="Theme Builder"
  description="Visual OKLCH-based theme builder for Urbicon UI. Pick your brand color and generate a complete design token palette."
/>

<DocsPageLayout
  title="Theme Builder"
  description="Pick your brand color and generate a matched palette: accent plus a neutral chassis, so surfaces, text and borders share its temperature. Uses OKLCH for consistent contrast across all shades."
  maxWidth="2xl"
  breadcrumbs={[{ label: 'Customization', href: resolve('/customization') }]}
>
  <div class="grid grid-cols-1 gap-8 xl:grid-cols-5">
    <!-- Controls -->
    <div class="xl:col-span-2">
      <Card class="border-border-subtle sticky top-8 shadow-[var(--blocks-shadow-md)]">
        <div class="space-y-6 p-6">
          <h2 class="text-text-primary text-lg font-semibold">Brand Color</h2>

          <!-- Hue Slider -->
          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="hue-slider" class="text-text-primary text-sm font-medium">Hue</label>
              <span class="text-text-tertiary font-mono text-xs">{brandHue}°</span>
            </div>
            <input
              id="hue-slider"
              type="range"
              min="0"
              max="360"
              step="1"
              bind:value={brandHue}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.6 0.15 0), oklch(0.6 0.15 30), oklch(0.6 0.15 60), oklch(0.6 0.15 90), oklch(0.6 0.15 120), oklch(0.6 0.15 150), oklch(0.6 0.15 180), oklch(0.6 0.15 210), oklch(0.6 0.15 240), oklch(0.6 0.15 270), oklch(0.6 0.15 300), oklch(0.6 0.15 330), oklch(0.6 0.15 360))"
            />
          </div>

          <!-- Chroma Slider -->
          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="chroma-slider" class="text-text-primary text-sm font-medium"
                >Chroma (Saturation)</label
              >
              <span class="text-text-tertiary font-mono text-xs">{brandChroma.toFixed(2)}</span>
            </div>
            <input
              id="chroma-slider"
              type="range"
              min="0.01"
              max="0.3"
              step="0.01"
              bind:value={brandChroma}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.58 0.01 {brandHue}), oklch(0.58 0.15 {brandHue}), oklch(0.58 0.3 {brandHue}))"
            />
          </div>

          <!-- Lightness Slider -->
          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="lightness-slider" class="text-text-primary text-sm font-medium"
                >Lightness</label
              >
              <span class="text-text-tertiary font-mono text-xs">{brandLightness.toFixed(2)}</span>
            </div>
            <input
              id="lightness-slider"
              type="range"
              min="0.3"
              max="0.75"
              step="0.01"
              bind:value={brandLightness}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.3 {brandChroma} {brandHue}), oklch(0.5 {brandChroma} {brandHue}), oklch(0.75 {brandChroma} {brandHue}))"
            />
          </div>

          <Separator />

          <h2 class="text-text-primary text-lg font-semibold">Secondary Color</h2>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="secondary-hue-slider" class="text-text-primary text-sm font-medium"
                >Hue</label
              >
              <div class="flex items-center gap-2">
                <span class="text-text-tertiary font-mono text-xs">{secondaryHue}°</span>
                <button
                  class="rounded-modify text-3xs border px-2 py-0.5 font-medium transition-colors {secondaryAuto
                    ? 'border-primary bg-primary-subtle text-primary'
                    : 'border-border-subtle text-text-tertiary hover:border-border-default'}"
                  onclick={() => {
                    secondaryAuto = !secondaryAuto;
                    if (secondaryAuto) secondaryHue = computeAutoSecondaryHue(brandHue);
                  }}
                >
                  Auto
                </button>
              </div>
            </div>
            <input
              id="secondary-hue-slider"
              type="range"
              min="0"
              max="360"
              step="1"
              bind:value={secondaryHue}
              disabled={secondaryAuto}
              class="h-3 w-full cursor-pointer appearance-none rounded-full disabled:opacity-50"
              style="background: linear-gradient(to right, oklch(0.55 0.12 0), oklch(0.55 0.12 60), oklch(0.55 0.12 120), oklch(0.55 0.12 180), oklch(0.55 0.12 240), oklch(0.55 0.12 300), oklch(0.55 0.12 360))"
            />
          </div>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="secondary-chroma-slider" class="text-text-primary text-sm font-medium"
                >Chroma</label
              >
              <span class="text-text-tertiary font-mono text-xs">{secondaryChroma.toFixed(2)}</span>
            </div>
            <input
              id="secondary-chroma-slider"
              type="range"
              min="0.01"
              max="0.25"
              step="0.01"
              bind:value={secondaryChroma}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.55 0.01 {secondaryHue}), oklch(0.55 0.12 {secondaryHue}), oklch(0.55 0.25 {secondaryHue}))"
            />
          </div>

          <div>
            <h3 class="text-text-primary mb-2 text-sm font-medium">Secondary Palette</h3>
            <div class="flex gap-1">
              {#each Object.entries(secondaryPalette) as [shade, color] (shade)}
                <div class="flex-1">
                  <div
                    class="rounded-modify mb-1 aspect-square w-full"
                    style="background: {color}"
                    title="{shade}: {color}"
                  ></div>
                  <div class="text-text-quaternary text-center font-mono text-[9px]">{shade}</div>
                </div>
              {/each}
            </div>
          </div>

          <Separator />

          <h2 class="text-text-primary text-lg font-semibold">Chassis (Neutral)</h2>
          <p class="text-text-tertiary -mt-3 text-xs leading-relaxed">
            The tint behind surfaces, text and borders. Match it to your accent so the whole UI
            shares one temperature instead of a fixed cool grey.
          </p>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="chassis-hue-slider" class="text-text-primary text-sm font-medium"
                >Hue</label
              >
              <div class="flex items-center gap-2">
                <span class="text-text-tertiary font-mono text-xs">{chassisHue}°</span>
                <button
                  class="rounded-modify text-3xs border px-2 py-0.5 font-medium transition-colors {chassisAuto
                    ? 'border-primary bg-primary-subtle text-primary'
                    : 'border-border-subtle text-text-tertiary hover:border-border-default'}"
                  onclick={() => {
                    chassisAuto = !chassisAuto;
                    if (chassisAuto) chassisHue = brandHue;
                  }}
                >
                  Auto
                </button>
              </div>
            </div>
            <input
              id="chassis-hue-slider"
              type="range"
              min="0"
              max="360"
              step="1"
              bind:value={chassisHue}
              disabled={chassisAuto}
              class="h-3 w-full cursor-pointer appearance-none rounded-full disabled:opacity-50"
              style="background: linear-gradient(to right, oklch(0.7 0.05 0), oklch(0.7 0.05 60), oklch(0.7 0.05 120), oklch(0.7 0.05 180), oklch(0.7 0.05 240), oklch(0.7 0.05 300), oklch(0.7 0.05 360))"
            />
          </div>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="chassis-tint-slider" class="text-text-primary text-sm font-medium"
                >Tint strength</label
              >
              <span class="text-text-tertiary font-mono text-xs"
                >{chassisTint === 0 ? 'Grayscale' : `${chassisTint.toFixed(2)}×`}</span
              >
            </div>
            <input
              id="chassis-tint-slider"
              type="range"
              min="0"
              max="1.5"
              step="0.05"
              bind:value={chassisTint}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.7 0 0), oklch(0.7 0.03 {chassisHue}), oklch(0.7 0.06 {chassisHue}))"
            />
          </div>

          <div>
            <h3 class="text-text-primary mb-2 text-sm font-medium">Chassis Palette</h3>
            <div class="flex gap-1">
              {#each chassisPalette as { shade, value } (shade)}
                <div class="flex-1">
                  <div
                    class="rounded-modify border-border-subtle mb-1 aspect-square w-full border"
                    style="background: {value}"
                    title="{shade}: {value}"
                  ></div>
                  <div class="text-text-quaternary text-center font-mono text-[8px]">{shade}</div>
                </div>
              {/each}
            </div>
          </div>

          <Separator />

          <!-- Border Radius -->
          <div>
            <span class="text-text-primary mb-2 block text-sm font-medium">Border Radius</span>
            <div class="flex flex-wrap gap-2">
              {#each radiusOptions as opt (opt.value)}
                <button
                  class="rounded-modify border px-3 py-1.5 text-xs font-medium transition-colors {radius ===
                  opt.value
                    ? 'border-primary bg-primary-subtle text-primary'
                    : 'border-border-subtle text-text-tertiary hover:border-border-default hover:text-text-secondary'}"
                  onclick={() => (radius = opt.value)}
                >
                  {opt.label}
                </button>
              {/each}
            </div>
            <p class="text-text-tertiary mt-2 text-xs leading-relaxed">
              This moves the base scale, which the
              <code class="text-text-primary">modify</code>,
              <code class="text-text-primary">contain</code> and
              <code class="text-text-primary">bridge</code> tiers read from — so fields, panels and
              the middle tier (Menu panels, chat bubbles) all follow. Pill-tier components (Button,
              Badge) keep their pill:
              <code class="text-text-primary">--radius-commit</code>
              is a literal, so set it yourself to square them. The radio dot has its own literal and stays
              a circle either way — see
              <a href={resolve('/customization/tier-system')} class="text-primary hover:underline"
                >Radius Tiers</a
              >.
            </p>
          </div>

          <Separator />

          <!-- Generated Palette -->
          <div>
            <h3 class="text-text-primary mb-3 text-sm font-medium">Generated Palette</h3>
            <div class="flex gap-1">
              {#each Object.entries(palette) as [shade, color] (shade)}
                <div class="flex-1">
                  <div
                    class="rounded-modify mb-1 aspect-square w-full"
                    style="background: {color}"
                    title="{shade}: {color}"
                  ></div>
                  <div class="text-text-quaternary text-center font-mono text-[9px]">{shade}</div>
                </div>
              {/each}
            </div>
          </div>

          <Separator />

          <!-- Quick Presets -->
          <div>
            <h3 class="text-text-primary mb-3 text-sm font-medium">Presets</h3>
            <div class="grid grid-cols-4 gap-2">
              {#each [{ name: 'Blue', h: 240, c: 0.15, l: 0.58 }, { name: 'Purple', h: 280, c: 0.15, l: 0.55 }, { name: 'Green', h: 140, c: 0.15, l: 0.55 }, { name: 'Red', h: 25, c: 0.18, l: 0.55 }, { name: 'Orange', h: 50, c: 0.18, l: 0.6 }, { name: 'Teal', h: 180, c: 0.12, l: 0.55 }, { name: 'Pink', h: 340, c: 0.18, l: 0.6 }, { name: 'Indigo', h: 260, c: 0.18, l: 0.5 }] as preset (preset.name)}
                <button
                  class="border-border-subtle hover:border-border-default rounded-contain flex flex-col items-center gap-1 border p-2 transition-colors hover:shadow-[var(--blocks-shadow-sm)]"
                  onclick={() => {
                    brandHue = preset.h;
                    brandChroma = preset.c;
                    brandLightness = preset.l;
                    secondaryAuto = true;
                  }}
                >
                  <div
                    class="h-6 w-6 rounded-full"
                    style="background: oklch({preset.l} {preset.c} {preset.h})"
                  ></div>
                  <span class="text-text-tertiary text-3xs">{preset.name}</span>
                </button>
              {/each}
            </div>
          </div>
        </div>
      </Card>
    </div>

    <!-- Preview + Output -->
    <div class="space-y-8 xl:col-span-3">
      {#if collisions.length > 0}
        <Alert intent="warning" variant="soft" title="Intent collision">
          <p class="leading-relaxed">
            {#each collisions as c (c.role + c.intent)}
              <span class="block">
                <strong>{c.role}</strong> sits {c.distance}° from
                <strong>{c.intent}</strong>
                (hue {c.intentHue}). A
                <code class="text-xs">{c.intent}</code> state will read as your accent, not as a status.
              </span>
            {/each}
          </p>
          <p class="mt-2 leading-relaxed">
            Fix it in your theme file: re-tune the colliding
            <code class="text-xs">--color-*</code> ramp 15–25° away (keep each stop's lightness and
            chroma, move only the hue).
            <a
              href={`${resolve('/customization/themes')}#create`}
              class="text-warning-emphasis underline">forest.css</a
            >
            does this for both
            <code class="text-xs">success</code> and <code class="text-xs">warning</code>. The
            builder flags it rather than "fixing" it, because which color moves is your call.
          </p>
        </Alert>
      {/if}

      <!-- Live Component Preview -->
      <div>
        <h2 class="text-text-primary mb-4 text-lg font-semibold">Live Preview</h2>
        <Card class="border-border-subtle shadow-[var(--blocks-shadow-md)]">
          <div class="space-y-6 p-6" style={previewStyle}>
            <!-- Buttons -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Buttons</h3>
              <div class="flex flex-wrap gap-3">
                <Button intent="primary" variant="filled">Primary</Button>
                <Button intent="secondary" variant="filled">Secondary</Button>
                <Button intent="primary" variant="outlined">Outlined</Button>
                <Button intent="primary" variant="ghost">Ghost</Button>
              </div>
            </div>

            <Separator />

            <!-- Badges -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Badges</h3>
              <div class="flex flex-wrap gap-2">
                <Badge intent="primary" variant="filled">Primary</Badge>
                <Badge intent="secondary" variant="filled">Secondary</Badge>
                <Badge intent="primary" variant="soft">Soft</Badge>
                <Badge intent="secondary" variant="soft">Soft</Badge>
              </div>
            </div>

            <Separator />

            <!-- Form Elements -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Form Elements</h3>
              <div class="flex flex-wrap items-center gap-4">
                <Checkbox label="Checkbox" checked intent="primary" />
                <Toggle checked intent="primary" />
              </div>
            </div>

            <Separator />

            <!-- Card with Avatar -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Composition</h3>
              <Card class="border-border-subtle">
                <div class="flex items-center gap-4 p-4">
                  <Avatar name="Theme Builder" size="lg" />
                  <div class="flex-1">
                    <p class="text-text-primary font-medium">Your Custom Theme</p>
                    <p class="text-text-tertiary text-sm">
                      Hue {brandHue}° · Chroma {brandChroma.toFixed(2)}
                    </p>
                  </div>
                  <Button intent="primary" size="sm">Apply</Button>
                </div>
              </Card>
            </div>

            <Separator />

            <!-- Alert -->
            <Alert intent="primary" variant="soft" size="sm">
              Soft fills like this one read the 50/900 stops of your generated ramp.
            </Alert>
          </div>
        </Card>
      </div>

      <!-- CSS Output -->
      <div>
        <div class="mb-4 flex items-center justify-between">
          <h2 class="text-text-primary text-lg font-semibold">CSS Output</h2>
          <Button
            size="sm"
            variant="outlined"
            intent={copied ? 'success' : 'neutral'}
            onclick={copyCSS}
          >
            {copied ? 'Copied!' : 'Copy CSS'}
          </Button>
        </div>
        <Card class="border-border-subtle shadow-[var(--blocks-shadow-md)]">
          <pre
            class="text-text-secondary overflow-x-auto p-6 font-mono text-sm leading-relaxed"><code
              >{cssOutput}</code
            ></pre>
        </Card>
      </div>

      <!-- Usage Instructions -->
      <div>
        <h2 class="text-text-primary mb-4 text-lg font-semibold">How to Use</h2>
        <Card class="border-border-subtle">
          <ol class="text-text-secondary space-y-4 p-6 text-sm">
            <li class="flex gap-3">
              <span
                class="bg-primary-subtle text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold"
                >1</span
              >
              <div>
                <p class="text-text-primary font-medium">Adjust the sliders</p>
                <p>
                  Pick a hue, chroma, and lightness that match your brand identity. Coming from a
                  hex value? Start from the preset nearest your brand, then nudge the hue until the
                  500 swatch matches.
                </p>
              </div>
            </li>
            <li class="flex gap-3">
              <span
                class="bg-primary-subtle text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold"
                >2</span
              >
              <div>
                <p class="text-text-primary font-medium">Copy the CSS output</p>
                <p>
                  Click "Copy CSS" and save it as
                  <code class="bg-surface-subtle rounded-modify px-1.5 py-0.5 text-xs"
                    >my-theme.css</code
                  >, or paste it at the end of app.css, below the imports.
                </p>
              </div>
            </li>
            <li class="flex gap-3">
              <span
                class="bg-primary-subtle text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold"
                >3</span
              >
              <div>
                <p class="text-text-primary font-medium">Import it after the base styles</p>
                <p>
                  In app.css:
                  <code class="bg-surface-subtle rounded-modify px-1.5 py-0.5 text-xs"
                    >@import '@urbicon-ui/blocks/style/index.css';</code
                  >
                  then
                  <code class="bg-surface-subtle rounded-modify px-1.5 py-0.5 text-xs"
                    >@import './my-theme.css';</code
                  >. The
                  <code class="bg-surface-subtle rounded-modify px-1.5 py-0.5 text-xs">@theme</code> block
                  needs Tailwind 4; it merges into the library tokens. If the builder flagged an intent
                  collision above, re-tune that ramp before shipping.
                </p>
              </div>
            </li>
          </ol>
        </Card>
      </div>
    </div>
  </div>
</DocsPageLayout>
