<script lang="ts">
  import SeoMeta from '$lib/SeoMeta.svelte';
  import { resolve } from '$app/paths';
  import {
    Alert,
    Avatar,
    Badge,
    Button,
    Card,
    Checkbox,
    Separator,
    Toggle
  } from '@urbicon-ui/blocks';
  import { DocsLayout as DocsPageLayout } from '@urbicon-ui/docs';

  let brandHue = $state(240);
  let brandChroma = $state(0.15);
  let brandLightness = $state(0.58);
  let secondaryHue = $state(280);
  let secondaryChroma = $state(0.12);
  let secondaryAuto = $state(true);
  // Chassis = the neutral ramp that surfaces/text/borders derive from. Auto
  // follows the brand hue so the whole UI shares the accent's temperature;
  // chassisTint scales the (already tiny) per-stop chroma — 0 = pure grayscale.
  let chassisHue = $state(240);
  let chassisAuto = $state(true);
  let chassisTint = $state(1);
  let radius = $state('md');
  let copied = $state(false);

  function computeAutoSecondaryHue(h: number): number {
    return (h + 40) % 360;
  }

  $effect(() => {
    if (secondaryAuto) {
      secondaryHue = computeAutoSecondaryHue(brandHue);
    }
  });

  $effect(() => {
    if (chassisAuto) {
      chassisHue = brandHue;
    }
  });

  // Foundation neutral ramp — lightness + base chroma per stop (hue 240 by
  // default). The builder keeps L fixed (so WCAG contrast is preserved) and
  // only shifts the hue + scales the chroma.
  const neutralRamp = [
    { shade: 25, l: 0.99, c: 0.002 },
    { shade: 50, l: 0.98, c: 0.005 },
    { shade: 100, l: 0.95, c: 0.008 },
    { shade: 200, l: 0.89, c: 0.012 },
    { shade: 300, l: 0.83, c: 0.014 },
    { shade: 400, l: 0.7, c: 0.015 },
    { shade: 500, l: 0.55, c: 0.016 },
    { shade: 600, l: 0.42, c: 0.017 },
    { shade: 650, l: 0.38, c: 0.016 },
    { shade: 700, l: 0.32, c: 0.016 },
    { shade: 750, l: 0.28, c: 0.014 },
    { shade: 800, l: 0.23, c: 0.015 },
    { shade: 850, l: 0.18, c: 0.014 },
    { shade: 900, l: 0.15, c: 0.012 },
    { shade: 950, l: 0.08, c: 0.008 }
  ] as const;

  function roundChroma(value: number): number {
    return Math.round(value * 10000) / 10000;
  }

  const chassisPalette = $derived(
    neutralRamp.map(({ shade, l, c }) => ({
      shade,
      value: oklch(l, roundChroma(c * chassisTint), chassisHue)
    }))
  );

  // The chassis equals the library default when hue is 240 at full tint —
  // no point emitting a no-op override in that case.
  const chassisIsDefault = $derived(chassisHue === 240 && chassisTint === 1);

  const radiusOptions = [
    { value: 'none', label: 'None', scale: 0 },
    { value: 'sm', label: 'Tight', scale: 0.5 },
    { value: 'md', label: 'Default', scale: 1 },
    { value: 'lg', label: 'Rounded', scale: 2 },
    { value: 'xl', label: 'Extra', scale: 3 },
    { value: 'full', label: 'Pill', scale: -1 }
  ];

  const baseRadii: Record<string, number> = {
    xs: 0.125,
    sm: 0.25,
    md: 0.375,
    lg: 0.5,
    xl: 0.75,
    '2xl': 1,
    '3xl': 1.5,
    '4xl': 2
  };

  const activeRadiusOption = $derived(radiusOptions.find((o) => o.value === radius)!);

  const radiusVars = $derived.by(() => {
    const opt = activeRadiusOption;
    if (opt.scale === 1) return {};
    const vars: Record<string, string> = {};
    for (const [name, base] of Object.entries(baseRadii)) {
      vars[`--radius-${name}`] =
        opt.scale === -1 ? '9999px' : `${(base * opt.scale).toFixed(3)}rem`;
    }
    return vars;
  });

  function oklch(l: number, c: number, h: number): string {
    return `oklch(${l} ${c} ${h})`;
  }

  function generatePalette(h: number, c: number, l500: number) {
    return {
      50: oklch(0.95, c * 0.2, h),
      100: oklch(0.9, c * 0.33, h),
      200: oklch(0.82, c * 0.53, h),
      300: oklch(0.74, c * 0.73, h),
      400: oklch(0.66, c * 0.87, h),
      500: oklch(l500, c, h),
      600: oklch(0.52, c, h),
      700: oklch(0.44, c * 0.87, h),
      800: oklch(0.36, c * 0.73, h),
      900: oklch(0.28, c * 0.53, h),
      950: oklch(0.18, c * 0.33, h)
    };
  }

  let palette = $derived(generatePalette(brandHue, brandChroma, brandLightness));
  let secondaryPalette = $derived(generatePalette(secondaryHue, secondaryChroma, 0.55));

  let cssOutput = $derived.by(() => {
    const chassisLabel = chassisTint === 0 ? 'grayscale' : `hue ${chassisHue}`;
    const lines = [
      `@theme {`,
      `  /* Generated by Urbicon UI Theme Builder */`,
      `  /* Primary Hue: ${brandHue} | Secondary Hue: ${secondaryHue} | Chassis: ${chassisLabel} */`,
      ``
    ];
    for (const [shade, value] of Object.entries(palette)) {
      lines.push(`  --color-primary-${shade}: ${value};`);
    }
    lines.push(``);
    for (const [shade, value] of Object.entries(secondaryPalette)) {
      lines.push(`  --color-secondary-${shade}: ${value};`);
    }
    if (!chassisIsDefault) {
      lines.push(``);
      lines.push(`  /* Chassis — neutral ramp re-tinted (${chassisLabel}) so surfaces, text`);
      lines.push(`     and borders share the accent's temperature. Only the hue/chroma`);
      lines.push(`     shift; lightness matches the foundation ramp (WCAG-safe). */`);
      for (const { shade, value } of chassisPalette) {
        lines.push(`  --color-neutral-${shade}: ${value};`);
      }
    }
    const rv = Object.entries(radiusVars);
    if (rv.length > 0) {
      lines.push(``);
      lines.push(`  /* Border Radius – ${activeRadiusOption.label} */`);
      for (const [name, value] of rv) {
        lines.push(`  ${name}: ${value};`);
      }
    }
    lines.push(`}`);
    return lines.join('\n');
  });

  let previewStyle = $derived.by(() => {
    const vars: string[] = [];
    for (const [shade, value] of Object.entries(palette)) {
      vars.push(`--color-primary-${shade}: ${value}`);
    }
    vars.push(`--color-primary: ${palette[600]}`);
    vars.push(`--color-primary-hover: ${palette[700]}`);
    vars.push(`--color-primary-active: ${palette[800]}`);
    vars.push(`--color-primary-subtle: ${palette[50]}`);
    vars.push(`--color-primary-emphasis: ${palette[900]}`);
    for (const [shade, value] of Object.entries(secondaryPalette)) {
      vars.push(`--color-secondary-${shade}: ${value}`);
    }
    vars.push(`--color-secondary: ${secondaryPalette[500]}`);
    vars.push(`--color-secondary-hover: ${secondaryPalette[600]}`);
    vars.push(`--color-secondary-active: ${secondaryPalette[700]}`);
    vars.push(`--color-secondary-subtle: ${secondaryPalette[50]}`);
    vars.push(`--color-secondary-emphasis: ${secondaryPalette[800]}`);
    const byShade = Object.fromEntries(chassisPalette.map((s) => [s.shade, s.value] as const));
    for (const { shade, value } of chassisPalette) {
      vars.push(`--color-neutral-${shade}: ${value}`);
    }
    // Re-declare the light-mode chassis-derived tokens. In an inline scope
    // the var() in the :root semantic definitions won't re-substitute against
    // the overridden neutral ramp on its own (the same trap editorial.css
    // solves), so push direct light-mode values mirroring semantic.css.
    vars.push(`--color-surface-quiet: ${byShade[25]}`);
    vars.push(`--color-surface-elevated: ${byShade[50]}`);
    vars.push(`--color-surface-subtle: ${byShade[50]}`);
    vars.push(`--color-surface-hover: ${byShade[100]}`);
    vars.push(`--color-surface-active: ${byShade[200]}`);
    vars.push(`--color-surface-interactive: ${byShade[100]}`);
    vars.push(`--color-text-primary: ${byShade[900]}`);
    vars.push(`--color-text-secondary: ${byShade[700]}`);
    vars.push(`--color-text-tertiary: ${byShade[600]}`);
    vars.push(`--color-text-quaternary: ${byShade[500]}`);
    vars.push(`--color-border-subtle: ${byShade[200]}`);
    vars.push(`--color-border-default: ${byShade[300]}`);
    vars.push(`--color-border-emphasis: ${byShade[400]}`);
    vars.push(`--color-border-strong: ${byShade[500]}`);
    for (const [name, value] of Object.entries(radiusVars)) {
      vars.push(`${name}: ${value}`);
    }
    return vars.join('; ');
  });

  async function copyCSS() {
    await navigator.clipboard.writeText(cssOutput);
    copied = true;
    setTimeout(() => (copied = false), 2000);
  }
</script>

<SeoMeta
  title="Theme Builder"
  description="Visual OKLCH-based theme builder for Urbicon UI. Pick your brand color and generate a complete design token palette."
/>

<DocsPageLayout
  title="Theme Builder"
  description="Pick your brand color and instantly generate a complete, perceptually-uniform palette — accent plus a matched neutral chassis so surfaces, text and borders share its temperature. Uses OKLCH for consistent contrast across all shades."
  maxWidth="2xl"
  breadcrumbs={[
    { label: 'Customization', href: resolve('/customization') },
    { label: 'Theme Builder' }
  ]}
>
  <div class="grid grid-cols-1 gap-8 xl:grid-cols-5">
    <!-- Controls -->
    <div class="xl:col-span-2">
      <Card class="border-border-subtle sticky top-8 shadow-[var(--blocks-shadow-md)]">
        <div class="space-y-6 p-6">
          <h2 class="text-text-primary text-lg font-semibold">Brand Color</h2>

          <!-- Hue Slider -->
          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="hue-slider" class="text-text-primary text-sm font-medium">Hue</label>
              <span class="text-text-tertiary font-mono text-xs">{brandHue}°</span>
            </div>
            <input
              id="hue-slider"
              type="range"
              min="0"
              max="360"
              step="1"
              bind:value={brandHue}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.6 0.15 0), oklch(0.6 0.15 30), oklch(0.6 0.15 60), oklch(0.6 0.15 90), oklch(0.6 0.15 120), oklch(0.6 0.15 150), oklch(0.6 0.15 180), oklch(0.6 0.15 210), oklch(0.6 0.15 240), oklch(0.6 0.15 270), oklch(0.6 0.15 300), oklch(0.6 0.15 330), oklch(0.6 0.15 360))"
            />
          </div>

          <!-- Chroma Slider -->
          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="chroma-slider" class="text-text-primary text-sm font-medium"
                >Chroma (Saturation)</label
              >
              <span class="text-text-tertiary font-mono text-xs">{brandChroma.toFixed(2)}</span>
            </div>
            <input
              id="chroma-slider"
              type="range"
              min="0.01"
              max="0.3"
              step="0.01"
              bind:value={brandChroma}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.58 0.01 {brandHue}), oklch(0.58 0.15 {brandHue}), oklch(0.58 0.3 {brandHue}))"
            />
          </div>

          <!-- Lightness Slider -->
          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="lightness-slider" class="text-text-primary text-sm font-medium"
                >Lightness</label
              >
              <span class="text-text-tertiary font-mono text-xs">{brandLightness.toFixed(2)}</span>
            </div>
            <input
              id="lightness-slider"
              type="range"
              min="0.3"
              max="0.75"
              step="0.01"
              bind:value={brandLightness}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.3 {brandChroma} {brandHue}), oklch(0.5 {brandChroma} {brandHue}), oklch(0.75 {brandChroma} {brandHue}))"
            />
          </div>

          <Separator />

          <h2 class="text-text-primary text-lg font-semibold">Secondary Color</h2>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="secondary-hue-slider" class="text-text-primary text-sm font-medium"
                >Hue</label
              >
              <div class="flex items-center gap-2">
                <span class="text-text-tertiary font-mono text-xs">{secondaryHue}°</span>
                <button
                  class="rounded-modify border px-2 py-0.5 text-[10px] font-medium transition-all {secondaryAuto
                    ? 'border-primary bg-primary-subtle text-primary'
                    : 'border-border-subtle text-text-tertiary hover:border-border-default'}"
                  onclick={() => {
                    secondaryAuto = !secondaryAuto;
                    if (secondaryAuto) secondaryHue = computeAutoSecondaryHue(brandHue);
                  }}
                >
                  Auto
                </button>
              </div>
            </div>
            <input
              id="secondary-hue-slider"
              type="range"
              min="0"
              max="360"
              step="1"
              bind:value={secondaryHue}
              disabled={secondaryAuto}
              class="h-3 w-full cursor-pointer appearance-none rounded-full disabled:opacity-50"
              style="background: linear-gradient(to right, oklch(0.55 0.12 0), oklch(0.55 0.12 60), oklch(0.55 0.12 120), oklch(0.55 0.12 180), oklch(0.55 0.12 240), oklch(0.55 0.12 300), oklch(0.55 0.12 360))"
            />
          </div>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="secondary-chroma-slider" class="text-text-primary text-sm font-medium"
                >Chroma</label
              >
              <span class="text-text-tertiary font-mono text-xs">{secondaryChroma.toFixed(2)}</span>
            </div>
            <input
              id="secondary-chroma-slider"
              type="range"
              min="0.01"
              max="0.25"
              step="0.01"
              bind:value={secondaryChroma}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.55 0.01 {secondaryHue}), oklch(0.55 0.12 {secondaryHue}), oklch(0.55 0.25 {secondaryHue}))"
            />
          </div>

          <div>
            <h3 class="text-text-primary mb-2 text-sm font-medium">Secondary Palette</h3>
            <div class="flex gap-1">
              {#each Object.entries(secondaryPalette) as [shade, color] (shade)}
                <div class="flex-1">
                  <div
                    class="rounded-modify mb-1 aspect-square w-full"
                    style="background: {color}"
                    title="{shade}: {color}"
                  ></div>
                  <div class="text-text-quaternary text-center font-mono text-[9px]">{shade}</div>
                </div>
              {/each}
            </div>
          </div>

          <Separator />

          <h2 class="text-text-primary text-lg font-semibold">Chassis (Neutral)</h2>
          <p class="text-text-tertiary -mt-3 text-xs leading-relaxed">
            The tint behind surfaces, text and borders. Match it to your accent so the whole UI
            shares one temperature instead of a fixed cool grey.
          </p>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="chassis-hue-slider" class="text-text-primary text-sm font-medium"
                >Hue</label
              >
              <div class="flex items-center gap-2">
                <span class="text-text-tertiary font-mono text-xs">{chassisHue}°</span>
                <button
                  class="rounded-modify border px-2 py-0.5 text-[10px] font-medium transition-all {chassisAuto
                    ? 'border-primary bg-primary-subtle text-primary'
                    : 'border-border-subtle text-text-tertiary hover:border-border-default'}"
                  onclick={() => {
                    chassisAuto = !chassisAuto;
                    if (chassisAuto) chassisHue = brandHue;
                  }}
                >
                  Auto
                </button>
              </div>
            </div>
            <input
              id="chassis-hue-slider"
              type="range"
              min="0"
              max="360"
              step="1"
              bind:value={chassisHue}
              disabled={chassisAuto}
              class="h-3 w-full cursor-pointer appearance-none rounded-full disabled:opacity-50"
              style="background: linear-gradient(to right, oklch(0.7 0.05 0), oklch(0.7 0.05 60), oklch(0.7 0.05 120), oklch(0.7 0.05 180), oklch(0.7 0.05 240), oklch(0.7 0.05 300), oklch(0.7 0.05 360))"
            />
          </div>

          <div>
            <div class="mb-2 flex items-center justify-between">
              <label for="chassis-tint-slider" class="text-text-primary text-sm font-medium"
                >Tint strength</label
              >
              <span class="text-text-tertiary font-mono text-xs"
                >{chassisTint === 0 ? 'Grayscale' : `${chassisTint.toFixed(2)}×`}</span
              >
            </div>
            <input
              id="chassis-tint-slider"
              type="range"
              min="0"
              max="1.5"
              step="0.05"
              bind:value={chassisTint}
              class="h-3 w-full cursor-pointer appearance-none rounded-full"
              style="background: linear-gradient(to right, oklch(0.7 0 0), oklch(0.7 0.03 {chassisHue}), oklch(0.7 0.06 {chassisHue}))"
            />
          </div>

          <div>
            <h3 class="text-text-primary mb-2 text-sm font-medium">Chassis Palette</h3>
            <div class="flex gap-1">
              {#each chassisPalette as { shade, value } (shade)}
                <div class="flex-1">
                  <div
                    class="rounded-modify border-border-subtle mb-1 aspect-square w-full border"
                    style="background: {value}"
                    title="{shade}: {value}"
                  ></div>
                  <div class="text-text-quaternary text-center font-mono text-[8px]">{shade}</div>
                </div>
              {/each}
            </div>
          </div>

          <Separator />

          <!-- Border Radius -->
          <div>
            <span class="text-text-primary mb-2 block text-sm font-medium">Border Radius</span>
            <div class="flex flex-wrap gap-2">
              {#each radiusOptions as opt (opt.value)}
                <button
                  class="rounded-modify border px-3 py-1.5 text-xs font-medium transition-all {radius ===
                  opt.value
                    ? 'border-primary bg-primary-subtle text-primary'
                    : 'border-border-subtle text-text-tertiary hover:border-border-default hover:text-text-secondary'}"
                  onclick={() => (radius = opt.value)}
                >
                  {opt.label}
                </button>
              {/each}
            </div>
          </div>

          <Separator />

          <!-- Generated Palette -->
          <div>
            <h3 class="text-text-primary mb-3 text-sm font-medium">Generated Palette</h3>
            <div class="flex gap-1">
              {#each Object.entries(palette) as [shade, color] (shade)}
                <div class="flex-1">
                  <div
                    class="rounded-modify mb-1 aspect-square w-full"
                    style="background: {color}"
                    title="{shade}: {color}"
                  ></div>
                  <div class="text-text-quaternary text-center font-mono text-[9px]">{shade}</div>
                </div>
              {/each}
            </div>
          </div>

          <Separator />

          <!-- Quick Presets -->
          <div>
            <h3 class="text-text-primary mb-3 text-sm font-medium">Presets</h3>
            <div class="grid grid-cols-4 gap-2">
              {#each [{ name: 'Blue', h: 240, c: 0.15, l: 0.58 }, { name: 'Purple', h: 280, c: 0.15, l: 0.55 }, { name: 'Green', h: 140, c: 0.15, l: 0.55 }, { name: 'Red', h: 25, c: 0.18, l: 0.55 }, { name: 'Orange', h: 50, c: 0.18, l: 0.6 }, { name: 'Teal', h: 180, c: 0.12, l: 0.55 }, { name: 'Pink', h: 340, c: 0.18, l: 0.6 }, { name: 'Indigo', h: 260, c: 0.18, l: 0.5 }] as preset (preset.name)}
                <button
                  class="border-border-subtle hover:border-border-default rounded-contain flex flex-col items-center gap-1 border p-2 transition-all hover:shadow-[var(--blocks-shadow-sm)]"
                  onclick={() => {
                    brandHue = preset.h;
                    brandChroma = preset.c;
                    brandLightness = preset.l;
                    secondaryAuto = true;
                  }}
                >
                  <div
                    class="h-6 w-6 rounded-full"
                    style="background: oklch({preset.l} {preset.c} {preset.h})"
                  ></div>
                  <span class="text-text-tertiary text-[10px]">{preset.name}</span>
                </button>
              {/each}
            </div>
          </div>
        </div>
      </Card>
    </div>

    <!-- Preview + Output -->
    <div class="space-y-8 xl:col-span-3">
      <!-- Live Component Preview -->
      <div>
        <h2 class="text-text-primary mb-4 text-lg font-semibold">Live Preview</h2>
        <Card class="border-border-subtle shadow-[var(--blocks-shadow-md)]">
          <div class="space-y-6 p-6" style={previewStyle}>
            <!-- Buttons -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Buttons</h3>
              <div class="flex flex-wrap gap-3">
                <Button intent="primary" variant="filled">Primary</Button>
                <Button intent="secondary" variant="filled">Secondary</Button>
                <Button intent="primary" variant="outlined">Outlined</Button>
                <Button intent="primary" variant="ghost">Ghost</Button>
              </div>
            </div>

            <Separator />

            <!-- Badges -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Badges</h3>
              <div class="flex flex-wrap gap-2">
                <Badge intent="primary" variant="filled">Primary</Badge>
                <Badge intent="secondary" variant="filled">Secondary</Badge>
                <Badge intent="primary" variant="soft">Soft</Badge>
                <Badge intent="secondary" variant="soft">Soft</Badge>
              </div>
            </div>

            <Separator />

            <!-- Form Elements -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Form Elements</h3>
              <div class="flex flex-wrap items-center gap-4">
                <Checkbox label="Checkbox" checked intent="primary" />
                <Toggle checked intent="primary" />
              </div>
            </div>

            <Separator />

            <!-- Card with Avatar -->
            <div>
              <h3 class="text-text-tertiary mb-3 text-sm font-medium">Composition</h3>
              <Card class="border-border-subtle">
                <div class="flex items-center gap-4 p-4">
                  <Avatar name="Theme Builder" size="lg" />
                  <div class="flex-1">
                    <p class="text-text-primary font-medium">Your Custom Theme</p>
                    <p class="text-text-tertiary text-sm">
                      Hue {brandHue}° · Chroma {brandChroma.toFixed(2)}
                    </p>
                  </div>
                  <Button intent="primary" size="sm">Apply</Button>
                </div>
              </Card>
            </div>

            <Separator />

            <!-- Alert -->
            <Alert intent="primary" variant="soft" size="sm">
              This preview updates live as you adjust the controls.
            </Alert>
          </div>
        </Card>
      </div>

      <!-- CSS Output -->
      <div>
        <div class="mb-4 flex items-center justify-between">
          <h2 class="text-text-primary text-lg font-semibold">CSS Output</h2>
          <Button
            size="sm"
            variant="outlined"
            intent={copied ? 'success' : 'neutral'}
            onclick={copyCSS}
          >
            {copied ? 'Copied!' : 'Copy CSS'}
          </Button>
        </div>
        <Card class="border-border-subtle shadow-[var(--blocks-shadow-md)]">
          <pre
            class="text-text-secondary overflow-x-auto p-6 font-mono text-sm leading-relaxed"><code
              >{cssOutput}</code
            ></pre>
        </Card>
      </div>

      <!-- Usage Instructions -->
      <div>
        <h2 class="text-text-primary mb-4 text-lg font-semibold">How to Use</h2>
        <Card class="border-border-subtle">
          <ol class="text-text-secondary space-y-4 p-6 text-sm">
            <li class="flex gap-3">
              <span
                class="bg-primary-subtle text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold"
                >1</span
              >
              <div>
                <p class="text-text-primary font-medium">Adjust the sliders</p>
                <p>Pick a hue, chroma, and lightness that match your brand identity.</p>
              </div>
            </li>
            <li class="flex gap-3">
              <span
                class="bg-primary-subtle text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold"
                >2</span
              >
              <div>
                <p class="text-text-primary font-medium">Copy the CSS output</p>
                <p>
                  Click "Copy CSS" and paste the <code
                    class="bg-surface-subtle rounded-modify px-1.5 py-0.5 text-xs">@theme</code
                  > block into your stylesheet.
                </p>
              </div>
            </li>
            <li class="flex gap-3">
              <span
                class="bg-primary-subtle text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold"
                >3</span
              >
              <div>
                <p class="text-text-primary font-medium">Overrides are applied automatically</p>
                <p>
                  Tailwind 4's @theme directive merges with the default tokens. All components pick
                  up your custom colors.
                </p>
              </div>
            </li>
          </ol>
        </Card>
      </div>
    </div>
  </div>
</DocsPageLayout>
