/**
 * Package-relative locator for the bundled Urbicon UI design knowledge.
 *
 * The bundle (`../content/`, produced at build/publish time by docs-gen's content
 * emitter) ships INSIDE this package, so every consumer — the remote MCP server,
 * the `urbicon` CLI, a CI hook — resolves it from its own install location
 * (`node_modules/@urbicon-ui/design-content/content/`) with no sibling-path
 * assumptions. This replaces the MCP server's former resolution out to
 * `apps/docs/static/` + `design-system/`, which only worked inside a full monorepo
 * checkout and left a published server empty (see DESIGN-MCP-V2 §A.0/2, A.2).
 *
 * `URBICON_CONTENT_DIR` overrides the base — for monorepo dev/tests pointing at a
 * freshly generated bundle, or to serve an alternate content set. The bundle is
 * git-ignored in dev and regenerated by `docs:gen:all`/`build`.
 */

import { readFile } from 'node:fs/promises';
import { dirname, normalize, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const moduleDir = dirname(fileURLToPath(import.meta.url));

/** The bundle directory: `<package>/content`, or the `URBICON_CONTENT_DIR` override. */
export function getContentDir(): string {
  return process.env.URBICON_CONTENT_DIR ?? resolve(moduleDir, '..', 'content');
}

/** The assembled component catalog (components + recipes + tags). */
export function getCatalogPath(): string {
  return resolve(getContentDir(), 'component-catalog.json');
}

/** The design-system copy: `principles.md` + `patterns/*.md`. */
export function getDesignSystemDir(): string {
  return resolve(getContentDir(), 'design-system');
}

/** The `llms-full` template that backs the guide resources. */
export function getTemplatePath(): string {
  return resolve(getContentDir(), 'guides', 'llms-full-template.md');
}

/** The parsed icon metadata (name → label/categories/keywords). */
export function getIconsPath(): string {
  return resolve(getContentDir(), 'icons.json');
}

/**
 * Valid component slug: lowercase alphanumeric segments joined by single hyphens.
 * Guards the path join below, since the slug reaches us from tool input.
 */
const SAFE_SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Resolve a component's `llm.txt` inside the bundle, under its catalog `group`
 * (e.g. `blocks/primitives`). Rejects unsafe slugs and any path that would escape
 * the content dir — the slug is the one part of this path that is caller-supplied.
 */
export function getComponentLlmPath(group: string, slug: string): string {
  if (!SAFE_SLUG.test(slug)) {
    throw new Error(`Invalid component slug: "${slug}"`);
  }

  const resolved = resolve(getContentDir(), group, slug, 'llm.txt');
  const base = normalize(getContentDir());

  if (!resolved.startsWith(base)) {
    throw new Error(`Path traversal blocked for slug: "${slug}"`);
  }

  return resolved;
}

/** Build provenance for the bundle (the version stamp surfaced in DESIGN-MCP-V2 Anhang B). */
export interface ContentMeta {
  /** The `@urbicon-ui/*` release this bundle was built from. */
  version: string;
  /** ISO-8601 timestamp of the build. */
  builtAt: string;
  /** Short fingerprint of the bundled catalog content. */
  contentHash: string;
}

/** Read the bundle's `meta.json`, or null when the bundle has not been generated yet. */
export async function loadContentMeta(): Promise<ContentMeta | null> {
  try {
    const raw = await readFile(resolve(getContentDir(), 'meta.json'), 'utf-8');
    return JSON.parse(raw) as ContentMeta;
  } catch {
    return null;
  }
}
