<script lang="ts">
  import SeoMeta from '$lib/SeoMeta.svelte';
  import { DocsLayout as DocsPageLayout, Section, CodeExample } from '@urbicon-ui/docs';
  import { Card } from '@urbicon-ui/blocks';
  import { resolveNav, type NavHref } from '$lib/navigation';

  type DocComponent = { name: string; href: NavHref; description: string };

  // Hand-curated — descriptions live here, per-component detail on the subpages.
  const pageAnatomy: DocComponent[] = [
    {
      name: 'DocsLayout',
      href: '/docs/components/docs-layout',
      description:
        'The page shell: collapsing hero, breadcrumbs, sticky table of contents with scroll-spy, stability badge, and source/related links.'
    },
    {
      name: 'Section',
      href: '/docs/components/section',
      description:
        'Numbered content sections with editorial markers, intent tinting, and anchor ids — the grid every page is built on.'
    },
    {
      name: 'TableOfContents',
      href: '/docs/components/table-of-contents',
      description:
        'Standalone scroll-spy table of contents — built into DocsLayout, usable on its own.'
    }
  ];

  const contentBlocks: DocComponent[] = [
    {
      name: 'CodeExample',
      href: '/docs/components/code-example',
      description:
        'Live preview and highlighted source side by side, with copy button and optional isolated rendering.'
    },
    {
      name: 'PlaygroundConfigurator',
      href: '/docs/components/playground-configurator',
      description:
        'Interactive prop playground: typed controls, conditional visibility, dirty state, and code generation.'
    },
    {
      name: 'ApiReference',
      href: '/docs/components/api-reference',
      description:
        'Prop tables rendered from the generated component metadata, with grouping and usage notes.'
    },
    {
      name: 'TypesReference',
      href: '/docs/components/types-reference',
      description: 'TypeScript interfaces and type aliases as a readable reference table.'
    },
    {
      name: 'InfoCard',
      href: '/docs/components/info-card',
      description: 'Compact intent-tinted callout cards for notes, warnings, and feature summaries.'
    }
  ];

  const navigation = [
    { id: 'overview', title: 'Overview' },
    { id: 'anatomy', title: 'Page Anatomy' },
    { id: 'content-blocks', title: 'Content Blocks' },
    { id: 'installation', title: 'Installation' }
  ];

  const usageCode =
    `<script lang="ts">
  import { DocsLayout, Section, CodeExample, ApiReference } from '@urbicon-ui/docs';
  import { componentData } from './api'; // generated by docs-gen
<` +
    `/script>

<DocsLayout title="Button" description="…" navigation={[…]}>
  <Section id="examples" title="Examples">
    <CodeExample title="Basic">
      <Button>Click me</Button>
    </CodeExample>
  </Section>
  <Section id="api" title="API Reference">
    <ApiReference props={componentData.props} />
  </Section>
</DocsLayout>`;
</script>

<SeoMeta
  title="Doc Components"
  description="The documentation kit this site is built with — layout shell, code examples, playgrounds, and generated API tables."
/>

<DocsPageLayout
  title="Doc Components"
  description="The documentation kit this site is built with — layout shell, code examples, playgrounds, and generated API tables."
  maxWidth="2xl"
  showToc={true}
  {navigation}
>
  <Section id="overview" title="Overview">
    <p class="text-text-secondary text-sm leading-relaxed">
      <code class="text-text-primary">@urbicon-ui/docs</code> is the documentation kit this site is built
      with — every page you are reading composes exactly these components. Use it to document your own
      component library or design system with the same editorial look: a page shell with scroll-spy navigation,
      live code examples, an interactive prop playground, and API tables fed by generated metadata.
    </p>
  </Section>

  <Section id="anatomy" title="Page Anatomy">
    <p class="text-text-secondary mb-4 text-sm leading-relaxed">
      The structural components a documentation page is assembled from.
    </p>
    <div class="grid gap-4 sm:grid-cols-2">
      {#each pageAnatomy as component (component.href)}
        <Card
          href={resolveNav(component.href)}
          class="border-border-subtle hover:border-primary/30 transition-colors"
        >
          <div class="p-5">
            <h3 class="text-text-primary mb-1 font-semibold">{component.name}</h3>
            <p class="text-text-tertiary text-sm">{component.description}</p>
          </div>
        </Card>
      {/each}
    </div>
  </Section>

  <Section id="content-blocks" title="Content Blocks">
    <p class="text-text-secondary mb-4 text-sm leading-relaxed">
      The building blocks that fill a page: examples, playgrounds, and reference tables.
    </p>
    <div class="grid gap-4 sm:grid-cols-2">
      {#each contentBlocks as component (component.href)}
        <Card
          href={resolveNav(component.href)}
          class="border-border-subtle hover:border-primary/30 transition-colors"
        >
          <div class="p-5">
            <h3 class="text-text-primary mb-1 font-semibold">{component.name}</h3>
            <p class="text-text-tertiary text-sm">{component.description}</p>
          </div>
        </Card>
      {/each}
    </div>
  </Section>

  <Section id="installation" title="Installation">
    <CodeExample
      title="Install"
      code={`bun add -d @urbicon-ui/docs`}
      language="bash"
      preview={false}
    />
    <div class="mt-6">
      <CodeExample
        title="A minimal documentation page"
        code={usageCode}
        language="svelte"
        preview={false}
      />
    </div>
  </Section>
</DocsPageLayout>
