<script lang="ts">
  import SeoMeta from '$lib/SeoMeta.svelte';
  import { DocsLayout as DocsPageLayout, Section, CodeExample } from '@urbicon-ui/docs';
  import { Card } from '@urbicon-ui/blocks';
  import { resolveNav, type NavHref } from '$lib/navigation';
  import docsCatalog from '../../../static/docs/_catalog.json';

  type DocComponent = { name: string; href: NavHref; description: string };

  /**
   * The index reads the generated catalogue, so a component cannot be shipped,
   * documented and missing here at the same time. Two of ten were, until
   * 2026-08: CodePanel and NoteList each had a page, a sidebar entry and a
   * `componentLinks` entry, and no card on the page that is supposed to list
   * them — `registry:lint` checks the other three registries, not this one.
   *
   * Only the split into the two groups is editorial (the catalogue has no
   * notion of "shell" versus "block"); everything a reader sees comes from the
   * component's own `@summary`, which `summary:lint` already gates. A component
   * not named below lands in Content Blocks rather than nowhere.
   */
  const ANATOMY: readonly string[] = ['DocsLayout', 'Section', 'TableOfContents'];

  const catalog = docsCatalog as ReadonlyArray<{
    name: string;
    slug: string;
    summary?: string;
    description: string;
  }>;

  const toCard = (entry: (typeof catalog)[number]): DocComponent => ({
    name: entry.name,
    href: `/docs/components/${entry.slug}` as NavHref,
    description: entry.summary ?? entry.description
  });

  const byName = (a: DocComponent, b: DocComponent) => a.name.localeCompare(b.name);
  const pageAnatomy = catalog
    .filter((e) => ANATOMY.includes(e.name))
    .map(toCard)
    .sort(byName);
  const contentBlocks = catalog
    .filter((e) => !ANATOMY.includes(e.name))
    .map(toCard)
    .sort(byName);

  const navigation = [
    { id: 'overview', title: 'Overview' },
    { id: 'anatomy', title: 'Page Anatomy' },
    { id: 'content-blocks', title: 'Content Blocks' },
    { id: 'installation', title: 'Installation' }
  ];

  const usageCode =
    `<script lang="ts">
  import { DocsLayout, Section, CodeExample, ApiReference } from '@urbicon-ui/docs';
  import { componentData } from './api'; // generated by docs-gen
<` +
    `/script>

<DocsLayout title="Button" description="…" navigation={[…]}>
  <Section id="examples" title="Examples">
    <CodeExample title="Basic">
      <Button>Click me</Button>
    </CodeExample>
  </Section>
  <Section id="api" title="API Reference">
    <ApiReference props={componentData.props} />
  </Section>
</DocsLayout>`;
</script>

<SeoMeta
  title="Doc Components"
  description="The documentation kit this site is built with — layout shell, code examples, playgrounds, and generated API tables."
/>

<DocsPageLayout
  title="Doc Components"
  description="The documentation kit this site is built with — layout shell, code examples, playgrounds, and generated API tables."
  maxWidth="2xl"
  showToc={true}
  {navigation}
>
  <Section id="overview" title="Overview">
    <p class="text-text-secondary text-sm leading-relaxed">
      <code class="text-text-primary">@urbicon-ui/docs</code> is the documentation kit this site is built
      with — every page you are reading composes exactly these components. Use it to document your own
      component library or design system with the same editorial look: a page shell with scroll-spy navigation,
      live code examples, an interactive prop playground, and API tables fed by generated metadata.
    </p>
  </Section>

  <Section id="anatomy" title="Page Anatomy">
    <p class="text-text-secondary mb-4 text-sm leading-relaxed">
      The structural components a documentation page is assembled from.
    </p>
    <div class="grid gap-4 sm:grid-cols-2">
      {#each pageAnatomy as component (component.href)}
        <Card
          href={resolveNav(component.href)}
          class="border-border-subtle hover:border-primary/30 transition-colors"
        >
          <div class="p-5">
            <h3 class="text-text-primary mb-1 font-semibold">{component.name}</h3>
            <p class="text-text-tertiary text-sm">{component.description}</p>
          </div>
        </Card>
      {/each}
    </div>
  </Section>

  <Section id="content-blocks" title="Content Blocks">
    <p class="text-text-secondary mb-4 text-sm leading-relaxed">
      The building blocks that fill a page: examples, playgrounds, and reference tables.
    </p>
    <div class="grid gap-4 sm:grid-cols-2">
      {#each contentBlocks as component (component.href)}
        <Card
          href={resolveNav(component.href)}
          class="border-border-subtle hover:border-primary/30 transition-colors"
        >
          <div class="p-5">
            <h3 class="text-text-primary mb-1 font-semibold">{component.name}</h3>
            <p class="text-text-tertiary text-sm">{component.description}</p>
          </div>
        </Card>
      {/each}
    </div>
  </Section>

  <Section id="installation" title="Installation">
    <CodeExample
      title="Install"
      code={`bun add -d @urbicon-ui/docs`}
      language="bash"
      preview={false}
    />
    <div class="mt-6">
      <CodeExample
        title="A minimal documentation page"
        code={usageCode}
        language="svelte"
        preview={false}
      />
    </div>
  </Section>
</DocsPageLayout>
