// DO NOT EDIT — generated by scripts/a2ui-axes-gen.ts (`bun run a2ui:axes`).
// Source: packages/design-content/content/component-catalog.json (docs-gen artifact).
//
// The variant-axis truth of the Urbicon components the A2UI catalog maps. The
// hand-curated registry couples to this (values ⊆ axis; default ===; every
// `urbicon` reference exists) so the catalog can never advertise a value the real
// component does not support. Regenerate after docs:gen with `bun run a2ui:axes`.

/** One variant axis: its allowed values (sorted) and documented default. */
export interface UrbiconAxis {
  readonly values: readonly string[];
  readonly default?: string;
}

/** Urbicon component name → axis name → axis. The Urbicon A2UI registry references these. */
export const URBICON_AXES: Readonly<Record<string, Readonly<Record<string, UrbiconAxis>>>> = {
  Accordion: {
    size: { values: ["lg", "md", "sm"], default: "md" },
    variant: { values: ["card", "default", "ghost"], default: "default" },
  },
  Alert: {
    intent: { values: ["danger", "info", "neutral", "primary", "success", "warning"], default: "primary" },
    size: { values: ["lg", "md", "sm"], default: "md" },
    variant: { values: ["filled", "inline", "soft"], default: "soft" },
  },
  Avatar: {
    intent: { values: ["danger", "neutral", "primary", "secondary", "success", "warning"], default: "neutral" },
    size: { values: ["2xl", "lg", "md", "sm", "xl", "xs"], default: "md" },
    variant: { values: ["circle", "rounded", "square"], default: "circle" },
  },
  Badge: {
    intent: { values: ["danger", "neutral", "primary", "secondary", "success", "warning"], default: "primary" },
    size: { values: ["lg", "md", "sm", "xs"], default: "md" },
    variant: { values: ["dot", "filled", "outlined", "soft"], default: "filled" },
  },
  Button: {
    intent: { values: ["danger", "neutral", "primary", "secondary", "success", "warning"], default: "neutral" },
    size: { values: ["2xs", "lg", "md", "sm", "xl", "xs"], default: "md" },
    variant: { values: ["filled", "ghost", "outlined", "text"], default: "filled" },
  },
  Card: {
    variant: { values: ["elevated", "floating", "outlined", "quiet"], default: "quiet" },
  },
  Checkbox: {
    intent: { values: ["danger", "neutral", "primary", "secondary", "success", "warning"], default: "primary" },
    size: { values: ["lg", "md", "sm", "xs"], default: "md" },
    variant: { values: ["filled", "ghost", "outlined"], default: "outlined" },
  },
  Input: {
    intent: { values: ["danger", "default", "success", "warning"], default: "default" },
    size: { values: ["lg", "md", "sm", "xl", "xs"], default: "md" },
    variant: { values: ["filled", "ghost", "outlined", "underline"], default: "outlined" },
  },
  Progress: {
    intent: { values: ["danger", "neutral", "primary", "secondary", "success", "warning"], default: "primary" },
    size: { values: ["lg", "md", "sm", "xs"], default: "md" },
  },
  RadioGroup: {
    orientation: { values: ["horizontal", "vertical"], default: "vertical" },
  },
  Select: {
    size: { values: ["lg", "md", "sm", "xl", "xs"], default: "md" },
    variant: { values: ["filled", "ghost", "outlined", "underline"], default: "outlined" },
  },
  Separator: {
    orientation: { values: ["horizontal", "vertical"], default: "horizontal" },
    size: { values: ["lg", "md", "sm"], default: "md" },
  },
  Slider: {
    intent: { values: ["danger", "neutral", "primary", "secondary", "success", "warning"], default: "primary" },
    size: { values: ["lg", "md", "sm"], default: "md" },
    variant: { values: ["default", "rail"], default: "default" },
  },
  Stepper: {
    orientation: { values: ["horizontal", "vertical"], default: "horizontal" },
    size: { values: ["lg", "md", "sm"], default: "md" },
    variant: { values: ["default", "minimal", "outlined"], default: "default" },
  },
  Textarea: {
    intent: { values: ["danger", "default", "success", "warning"], default: "default" },
    size: { values: ["lg", "md", "sm", "xl", "xs"], default: "md" },
  },
  TimeInput: {
    intent: { values: ["danger", "default", "success", "warning"], default: "default" },
    size: { values: ["lg", "md", "sm"], default: "md" },
    variant: { values: ["filled", "ghost", "outlined"], default: "outlined" },
  },
  Toggle: {
    intent: { values: ["danger", "neutral", "primary", "secondary", "success", "warning"], default: "primary" },
    size: { values: ["lg", "md", "sm", "xs"], default: "md" },
    variant: { values: ["default", "dot"], default: "default" },
  },
};
