#!/usr/bin/env bun
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Generate the Urbicon A2UI catalog's *variant-axis truth* from the docs-gen
 * component catalog.
 *
 * The Urbicon A2UI registry (`packages/blocks/src/lib/components/Chat/A2UIView/
 * urbicon/a2ui-urbicon-registry.ts`) is HAND-curated (descriptions, childId
 * conventions, prop whitelist), but the axis VALUES it may reference — a
 * Button's `intent`/`size`/`variant` sets and defaults — are library truth that
 * drifts as components evolve. This script emits that truth as a checked-in,
 * DO-NOT-EDIT module (`urbicon/urbicon-axes.gen.ts`), and a blocks-internal test
 * couples the registry to it (curated `values ⊆ axis`; `default ===`; every
 * `urbicon` reference exists). Output is fully deterministic — components, axes
 * and values are sorted, and there is NO timestamp — so `--check` is a stable
 * CI gate that only fails on a real drift.
 *
 * Source: `packages/design-content/content/component-catalog.json` — a docs-gen
 * build artifact (git-ignored; produced by `docs:gen:all` / `build`). This
 * script therefore runs AFTER docs:gen in CI. Fail-loud when the source is
 * missing rather than emitting an empty/partial file.
 *
 * Usage:
 *   bun run a2ui:axes         # --write: regenerate the checked-in file
 *   bun run a2ui:axes:check   # --check: fail (with a diff hint) if it is stale
 */

const ROOT = resolve(import.meta.dirname, '..');
const SOURCE = resolve(ROOT, 'packages/design-content/content/component-catalog.json');
const OUT = resolve(
  ROOT,
  'packages/blocks/src/lib/components/Chat/A2UIView/urbicon/urbicon-axes.gen.ts'
);

/**
 * The Urbicon components whose axes the A2UI catalog may map. Emitting a fixed
 * set (rather than every catalog component) keeps the generated file focused and
 * stable: an unrelated component gaining a variant never churns this file. A
 * registry `urbicon` reference outside this set fails the drift test, which is
 * the signal to add it here.
 */
const SOURCE_COMPONENTS = [
  'Accordion',
  'Alert',
  'Avatar',
  'Badge',
  'Button',
  'Card',
  'Checkbox',
  'DatePicker',
  'EmptyState',
  'Input',
  'Progress',
  'RadioGroup',
  'Select',
  'Separator',
  'Slider',
  'Stepper',
  'Textarea',
  'TimeInput',
  'Toggle'
] as const;

/** The style axes the catalog exposes. Functional/state variants (loading, active, …) are ignored. */
const AXIS_NAMES = new Set(['intent', 'size', 'variant', 'orientation']);

interface CatalogVariant {
  name: string;
  values: string[];
  default?: string;
}
interface CatalogComponent {
  name: string;
  variants?: CatalogVariant[];
}

type AxisMap = Record<string, Record<string, { values: string[]; default?: string }>>;

function buildAxisMap(): AxisMap {
  if (!existsSync(SOURCE)) {
    throw new Error(
      `a2ui-axes-gen: source catalog not found at ${SOURCE}\n` +
        'Run `bun run docs:gen:all` (or a full build) first — the axes generator ' +
        'reads the docs-gen component catalog.'
    );
  }
  const catalog = JSON.parse(readFileSync(SOURCE, 'utf8')) as { components?: CatalogComponent[] };
  const byName = new Map(
    (catalog.components ?? []).map((component) => [component.name, component])
  );

  const out: AxisMap = {};
  for (const name of [...SOURCE_COMPONENTS].sort()) {
    const component = byName.get(name);
    if (!component) {
      throw new Error(
        `a2ui-axes-gen: component "${name}" is in SOURCE_COMPONENTS but not in the catalog. ` +
          'Fix the list or regenerate the catalog.'
      );
    }
    const axes: Record<string, { values: string[]; default?: string }> = {};
    for (const variant of component.variants ?? []) {
      if (!AXIS_NAMES.has(variant.name)) continue;
      axes[variant.name] = {
        values: [...variant.values].sort(),
        ...(variant.default !== undefined ? { default: variant.default } : {})
      };
    }
    if (Object.keys(axes).length > 0) out[name] = axes;
  }
  return out;
}

function render(map: AxisMap): string {
  const lines: string[] = [];
  lines.push('// DO NOT EDIT — generated by scripts/a2ui-axes-gen.ts (`bun run a2ui:axes`).');
  lines.push(
    '// Source: packages/design-content/content/component-catalog.json (docs-gen artifact).'
  );
  lines.push('//');
  lines.push('// The variant-axis truth of the Urbicon components the A2UI catalog maps. The');
  lines.push('// hand-curated registry couples to this (values ⊆ axis; default ===; every');
  lines.push('// `urbicon` reference exists) so the catalog can never advertise a value the real');
  lines.push('// component does not support. Regenerate after docs:gen with `bun run a2ui:axes`.');
  lines.push('');
  lines.push('/** One variant axis: its allowed values (sorted) and documented default. */');
  lines.push('export interface UrbiconAxis {');
  lines.push('  readonly values: readonly string[];');
  lines.push('  readonly default?: string;');
  lines.push('}');
  lines.push('');
  lines.push(
    '/** Urbicon component name → axis name → axis. The Urbicon A2UI registry references these. */'
  );
  lines.push(
    'export const URBICON_AXES: Readonly<Record<string, Readonly<Record<string, UrbiconAxis>>>> = {'
  );
  const componentNames = Object.keys(map).sort();
  for (const componentName of componentNames) {
    lines.push(`  ${componentName}: {`);
    const axisNames = Object.keys(map[componentName]).sort();
    for (const axisName of axisNames) {
      const axis = map[componentName][axisName];
      const values = axis.values.map((value) => JSON.stringify(value)).join(', ');
      const def = axis.default !== undefined ? `, default: ${JSON.stringify(axis.default)}` : '';
      lines.push(`    ${axisName}: { values: [${values}]${def} },`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const mode = process.argv.includes('--check') ? 'check' : 'write';
  const generated = render(buildAxisMap());

  if (mode === 'check') {
    const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (current !== generated) {
      console.error(
        'a2ui-axes-gen: urbicon-axes.gen.ts is STALE (out of sync with the component catalog).\n' +
          'Run `bun run a2ui:axes` to regenerate, then commit the result.'
      );
      process.exit(1);
    }
    console.log('a2ui-axes-gen: urbicon-axes.gen.ts is up to date.');
    return;
  }

  writeFileSync(OUT, generated);
  console.log(`a2ui-axes-gen: wrote ${OUT}`);
}

main();
