/**
 * GENERATED by apps/docs/scripts/channels-gen.ts — do not edit by hand.
 * Regenerate with `bun apps/docs/scripts/channels-gen.ts`.
 *
 * Kanal-Register der Landing (Struktur v2): ein Farbrad, eine Formel
 * (Cusp-Vollton + Tiefe L 0.32), on-Farbe per Kontrastmessung. Themen-Kanäle
 * (Kacheln) und Familien-Kanäle (Katalog-Familien) referenzieren dieselben
 * Einträge. Grün/Gelb sind Erzählfarben und keiner Familie zugeordnet.
 *
 * Vier Stufen pro Hue, weil der Kanal vier Rollen hat:
 *   solid      — die Vollton-FLÄCHE (Kacheln). Auf Papier unlesbar, per Konstruktion.
 *   deep       — Text auf dem Vollton, Fläche im Dark Mode.
 *   accent     — der Kanal auf hellem Grund als Fläche, Linie, Marke, Indikator,
 *                große Schrift: die hellste Stufe mit ≥3:1 gegen Papier.
 *   accentText — derselbe Kanal als kleiner Fließtext: die hellste Stufe mit
 *                ≥4.5:1 gegen das dunkelste helle Papier.
 * Zwei Stufen für zwei WCAG-Schwellen. Jede dunklere Stufe lässt die zehn Hues
 * ineinanderlaufen, jede hellere ist in ihrer Rolle nicht mehr lesbar.
 */

export interface Channel {
  name: string;
  /** `null` = unbunter Ink-Kanal. */
  hue: number | null;
  /** Cusp-Vollton — die Fläche. */
  solid: string;
  /** Tiefe im selben Hue — Text auf hellen Cusps, Fläche im Dark Mode. */
  deep: string;
  /** Gemessene on-Farbe für Text auf dem Vollton (Tiefe oder Paper). */
  on: string;
  /**
   * Der Kanal auf hellem Grund: die hellste Stufe mit ≥ 3:1 gegen Papier.
   * Für Flächen, Linien, Indikatoren, Marken und große Schrift — NICHT für
   * kleinen Fließtext, der 4.5:1 braucht: dafür ist `accentText` da.
   *
   * Auf DUNKLEM Grund ist diese Stufe auch die Textfarbe (4.9:1 gegen das
   * Doku-Nachtpapier) — dort wäre `accentText` mit 3.2:1 zu dunkel.
   */
  accent: string;
  /** Dunkle on-Farbe für Text auf der Akzent-FLÄCHE (helle trägt dort nicht). */
  accentOn: string;
  /** Gemessener Kontrast der Akzent-Stufe gegen das Papier. */
  accentOnPaper: number;
  /**
   * Der Kanal als kleiner Fließtext auf HELLEM Grund: die hellste Stufe mit
   * ≥ 4.5:1. Rund L 0.53–0.59 — satter als `accent`, aber weit über der
   * Tiefe, die zehn Hues bleiben unterscheidbar. Als FÜLLUNG trägt sie das
   * helle Papier als on-Farbe (dieselbe Messung, andere Richtung).
   */
  accentText: string;
  /** Gemessener Kontrast der Text-Stufe gegen das dunkelste helle Papier. */
  accentTextOnPaper: number;
  /** WCAG-Kontrast Vollton↔Tiefe (0 beim Ink-Kanal). */
  pairContrast: number;
}

export const CHANNELS = {
  orange: {
    name: 'orange',
    hue: 40,
    solid: 'oklch(0.68 0.209 40)',
    deep: 'oklch(0.32 0.09 40)',
    on: 'oklch(0.32 0.09 40)',
    accent: 'oklch(0.67 0.21 40)',
    accentOn: 'oklch(0.2 0.05 40)',
    accentOnPaper: 3,
    accentText: 'oklch(0.564 0.177 40)',
    accentTextOnPaper: 4.5,
    pairContrast: 4.2
  },
  yellow: {
    name: 'yellow',
    hue: 100,
    solid: 'oklch(0.91 0.184 100)',
    deep: 'oklch(0.32 0.067 100)',
    on: 'oklch(0.32 0.067 100)',
    accent: 'oklch(0.645 0.134 100)',
    accentOn: 'oklch(0.2 0.042 100)',
    accentOnPaper: 3,
    accentText: 'oklch(0.543 0.113 100)',
    accentTextOnPaper: 4.5,
    pairContrast: 9.8
  },
  green: {
    name: 'green',
    hue: 145,
    solid: 'oklch(0.87 0.267 145)',
    deep: 'oklch(0.32 0.09 145)',
    on: 'oklch(0.32 0.09 145)',
    accent: 'oklch(0.627 0.197 145)',
    accentOn: 'oklch(0.2 0.05 145)',
    accentOnPaper: 3,
    accentText: 'oklch(0.528 0.166 145)',
    accentTextOnPaper: 4.5,
    pairContrast: 9
  },
  teal: {
    name: 'teal',
    hue: 175,
    solid: 'oklch(0.89 0.164 175)',
    deep: 'oklch(0.32 0.06 175)',
    on: 'oklch(0.32 0.06 175)',
    accent: 'oklch(0.632 0.119 175)',
    accentOn: 'oklch(0.2 0.038 175)',
    accentOnPaper: 3,
    accentText: 'oklch(0.532 0.1 175)',
    accentTextOnPaper: 4.5,
    pairContrast: 9.5
  },
  cyan: {
    name: 'cyan',
    hue: 200,
    solid: 'oklch(0.88 0.147 200)',
    deep: 'oklch(0.32 0.054 200)',
    on: 'oklch(0.32 0.054 200)',
    accent: 'oklch(0.635 0.108 200)',
    accentOn: 'oklch(0.2 0.034 200)',
    accentOnPaper: 3,
    accentText: 'oklch(0.535 0.091 200)',
    accentTextOnPaper: 4.5,
    pairContrast: 9.1
  },
  azure: {
    name: 'azure',
    hue: 230,
    solid: 'oklch(0.76 0.148 230)',
    deep: 'oklch(0.32 0.064 230)',
    on: 'oklch(0.32 0.064 230)',
    accent: 'oklch(0.64 0.128 230)',
    accentOn: 'oklch(0.2 0.04 230)',
    accentOnPaper: 3,
    accentText: 'oklch(0.539 0.107 230)',
    accentTextOnPaper: 4.5,
    pairContrast: 6
  },
  blue: {
    name: 'blue',
    hue: 255,
    solid: 'oklch(0.63 0.201 255)',
    deep: 'oklch(0.32 0.09 255)',
    on: 'oklch(0.97 0.002 100)',
    accent: 'oklch(0.65 0.19 255)',
    accentOn: 'oklch(0.2 0.05 255)',
    accentOnPaper: 3,
    accentText: 'oklch(0.549 0.181 255)',
    accentTextOnPaper: 4.5,
    pairContrast: 3.6
  },
  purple: {
    name: 'purple',
    hue: 310,
    solid: 'oklch(0.6 0.295 310)',
    deep: 'oklch(0.32 0.09 310)',
    on: 'oklch(0.97 0.002 100)',
    accent: 'oklch(0.675 0.233 310)',
    accentOn: 'oklch(0.2 0.05 310)',
    accentOnPaper: 3,
    accentText: 'oklch(0.586 0.296 310)',
    accentTextOnPaper: 4.5,
    pairContrast: 2.8
  },
  magenta: {
    name: 'magenta',
    hue: 330,
    solid: 'oklch(0.7 0.31 330)',
    deep: 'oklch(0.32 0.09 330)',
    on: 'oklch(0.32 0.09 330)',
    accent: 'oklch(0.69 0.314 330)',
    accentOn: 'oklch(0.2 0.05 330)',
    accentOnPaper: 3,
    accentText: 'oklch(0.581 0.265 330)',
    accentTextOnPaper: 4.5,
    pairContrast: 4.2
  },
  red: {
    name: 'red',
    hue: 15,
    solid: 'oklch(0.64 0.249 15)',
    deep: 'oklch(0.32 0.09 15)',
    on: 'oklch(0.97 0.002 100)',
    accent: 'oklch(0.674 0.217 15)',
    accentOn: 'oklch(0.2 0.05 15)',
    accentOnPaper: 3,
    accentText: 'oklch(0.574 0.23 15)',
    accentTextOnPaper: 4.5,
    pairContrast: 3.5
  },
  ink: {
    name: 'ink',
    hue: null,
    solid: 'oklch(0.35 0.006 100)',
    deep: 'oklch(0.2 0.006 100)',
    on: 'oklch(0.97 0.002 100)',
    accent: 'oklch(0.35 0.006 100)',
    accentOn: 'oklch(0.97 0.002 100)',
    accentOnPaper: 10.4,
    accentText: 'oklch(0.35 0.006 100)',
    accentTextOnPaper: 10.3,
    pairContrast: 0
  }
} as const satisfies Record<string, Channel>;

export type ChannelName = keyof typeof CHANNELS;

/** Ebene 1 — Kachel → Kanal (Erzählung). */
export const TILE_CHANNEL = {
  blocks: 'orange',
  table: 'cyan',
  a2ui: 'magenta',
  agents: 'green',
  more: 'yellow'
} as const satisfies Record<string, ChannelName>;

/** Ebene 2 — Familie → Kanal (Struktur: Zeile 2 der Landing UND die Doku-Räume). */
export const FAMILY_CHANNEL = {
  action: 'orange',
  data: 'cyan',
  ai: 'magenta',
  form: 'blue',
  display: 'azure',
  navigation: 'teal',
  overlay: 'purple',
  feedback: 'red',
  layout: 'ink'
} as const satisfies Record<string, ChannelName>;

/** Kanal einer Katalog-Zeile — unbekannte Familien fallen ehrlich auf Ink. */
export function channelForFamily(family: string): Channel {
  return CHANNELS[(FAMILY_CHANNEL as Record<string, ChannelName>)[family] ?? 'ink'];
}
