/**
 * GENERATED by apps/docs/scripts/channels-gen.ts — do not edit by hand.
 * Regenerate with `bun apps/docs/scripts/channels-gen.ts`.
 *
 * Doku-Route → Kanal. Eine Komponentenseite trägt die Farbe ihrer FAMILIE
 * (`tags[0]` im docs-gen-Katalog), nicht die ihres Produktbereichs — dieselbe
 * Zuordnung, die Zeile 2 der Landing zeigt. Alles andere (Übersichten,
 * /recipes, /icons, /getting-started …) fällt auf den Kanal seines Bereichs
 * zurück; `/blocks`, `/table` und `/ai` erben dabei den Kachel-Kanal aus
 * Zeile 1.
 *
 * Die Tabelle ist aus den Katalogen erzeugt und eingecheckt: die
 * `_catalog.json` sind git-ignorierte docs-gen-Artefakte, ein frischer
 * Worktree hätte sie nicht. Neue Komponente ⇒ `bun run docs:gen:all`, dann
 * diesen Generator.
 */

import { CHANNELS, type Channel, type ChannelName } from './channels';

/** Pfad → Kanal, für jede Komponentenseite im Katalog. */
export const ROUTE_CHANNEL = {
  '/auth/components/account-settings': 'blue',
  '/auth/components/forgot-password-page': 'blue',
  '/auth/components/invitation-manager': 'blue',
  '/auth/components/login-page': 'blue',
  '/auth/components/notification-badge': 'red',
  '/auth/components/notification-center': 'red',
  '/auth/components/notification-listener': 'cyan',
  '/auth/components/passkey-manager': 'blue',
  '/auth/components/push-permission-prompt': 'red',
  '/auth/components/register-page': 'blue',
  '/auth/components/reset-password-page': 'blue',
  '/auth/components/session-manager': 'azure',
  '/auth/components/two-factor-manager': 'blue',
  '/auth/components/verify-email-page': 'red',
  '/blocks/components/a2-ui-view': 'magenta',
  '/blocks/components/area-chart': 'azure',
  '/blocks/components/avatar-group': 'azure',
  '/blocks/components/bar-chart': 'azure',
  '/blocks/components/calendar': 'azure',
  '/blocks/components/chart-frame': 'ink',
  '/blocks/components/chat': 'magenta',
  '/blocks/components/chat-message': 'magenta',
  '/blocks/components/chat-message-list': 'magenta',
  '/blocks/components/citation-chip': 'magenta',
  '/blocks/components/code-block': 'magenta',
  '/blocks/components/command-palette': 'orange',
  '/blocks/components/composition-bar': 'azure',
  '/blocks/components/copy-button': 'orange',
  '/blocks/components/currency-input': 'blue',
  '/blocks/components/date-picker': 'blue',
  '/blocks/components/date-range-picker': 'blue',
  '/blocks/components/donut-chart': 'azure',
  '/blocks/components/empty-state': 'ink',
  '/blocks/components/file-upload': 'blue',
  '/blocks/components/guide': 'purple',
  '/blocks/components/guide-article': 'azure',
  '/blocks/components/guide-beacon': 'red',
  '/blocks/components/guide-hint': 'purple',
  '/blocks/components/guide-marker': 'orange',
  '/blocks/components/guide-mention': 'teal',
  '/blocks/components/guide-panel': 'purple',
  '/blocks/components/guide-provider': 'purple',
  '/blocks/components/guide-ref': 'teal',
  '/blocks/components/line-chart': 'azure',
  '/blocks/components/locale-switcher': 'blue',
  '/blocks/components/number-input': 'blue',
  '/blocks/components/pin-input': 'blue',
  '/blocks/components/planner': 'azure',
  '/blocks/components/prompt-input': 'magenta',
  '/blocks/components/qr-code': 'azure',
  '/blocks/components/reasoning-disclosure': 'magenta',
  '/blocks/components/sankey': 'azure',
  '/blocks/components/sidebar-layout': 'ink',
  '/blocks/components/sparkline': 'azure',
  '/blocks/components/streaming-markdown': 'magenta',
  '/blocks/components/theme-switcher': 'orange',
  '/blocks/components/time-input': 'blue',
  '/blocks/components/tool-call-card': 'magenta',
  '/blocks/primitives/accordion': 'ink',
  '/blocks/primitives/alert': 'red',
  '/blocks/primitives/avatar': 'azure',
  '/blocks/primitives/badge': 'red',
  '/blocks/primitives/breadcrumb': 'teal',
  '/blocks/primitives/button': 'orange',
  '/blocks/primitives/button-group': 'orange',
  '/blocks/primitives/card': 'ink',
  '/blocks/primitives/checkbox': 'blue',
  '/blocks/primitives/collapsible': 'ink',
  '/blocks/primitives/combobox': 'blue',
  '/blocks/primitives/confirm-dialog': 'purple',
  '/blocks/primitives/dialog': 'purple',
  '/blocks/primitives/drawer': 'purple',
  '/blocks/primitives/form-field': 'blue',
  '/blocks/primitives/input': 'blue',
  '/blocks/primitives/journey-timeline': 'teal',
  '/blocks/primitives/kbd': 'azure',
  '/blocks/primitives/menu': 'orange',
  '/blocks/primitives/pagination': 'teal',
  '/blocks/primitives/popover': 'purple',
  '/blocks/primitives/progress': 'red',
  '/blocks/primitives/radio-group': 'blue',
  '/blocks/primitives/scroller': 'ink',
  '/blocks/primitives/segment-group': 'teal',
  '/blocks/primitives/select': 'blue',
  '/blocks/primitives/separator': 'ink',
  '/blocks/primitives/sidebar': 'ink',
  '/blocks/primitives/skeleton': 'red',
  '/blocks/primitives/slider': 'blue',
  '/blocks/primitives/spinner': 'red',
  '/blocks/primitives/split-pane': 'ink',
  '/blocks/primitives/stepper': 'teal',
  '/blocks/primitives/tab': 'teal',
  '/blocks/primitives/textarea': 'blue',
  '/blocks/primitives/toast': 'red',
  '/blocks/primitives/toggle': 'blue',
  '/blocks/primitives/toolbar': 'orange',
  '/blocks/primitives/tooltip': 'azure',
  '/table/table': 'cyan'
} as const satisfies Record<string, ChannelName>;

/** Bereich (oberstes Routensegment) → Kanal, für alles andere. */
export const AREA_CHANNEL = {
  blocks: 'orange',
  table: 'cyan',
  ai: 'magenta',
  auth: 'blue'
} as const satisfies Record<string, ChannelName>;

/** Kanal für jede Seite ohne eigenen Bereich (Impressum, Changelog, /icons …). */
export const DEFAULT_CHANNEL: ChannelName = 'orange';

/**
 * Der Kanalname einer Doku-Route — das, was `+layout.svelte` als
 * `data-room` stempelt. Erst die Komponentenseite (Familie), dann der
 * Bereich, dann der Default.
 */
export function channelNameForRoute(pathname: string): ChannelName {
  const path = pathname.replace(/\/+$/, '') || '/';
  const exact = (ROUTE_CHANNEL as Record<string, ChannelName>)[path];
  if (exact) return exact;
  const area = path.split('/')[1] ?? '';
  return (AREA_CHANNEL as Record<string, ChannelName>)[area] ?? DEFAULT_CHANNEL;
}

/** Derselbe Aufschlag als voller Registereintrag (Stufen, Hue, Messwerte). */
export function channelForRoute(pathname: string): Channel {
  return CHANNELS[channelNameForRoute(pathname)];
}
